from .legacy import CvSkillSerializer, UserCvSerializer
from .v2 import (
    CvApplySampleSerializer,
    CvAssetSerializer,
    CvAssetUploadSerializer,
    CvDraftSerializer,
    CvDraftWriteSerializer,
    CvExportCreateSerializer,
    CvExportSerializer,
    CvSharedLinkCreateSerializer,
    CvSharedLinkSerializer,
    CvTemplateSwitchSerializer,
    CvV2CreateSerializer,
    CvV2DuplicateSerializer,
    CvV2ImportSerializer,
    CvV2MetadataUpdateSerializer,
    CvV2Serializer,
    CvVersionSerializer,
    CvVersionSummarySerializer,
    SharedCvVersionSerializer,
)

__all__ = [
    'CvApplySampleSerializer',
    'CvAssetSerializer',
    'CvAssetUploadSerializer',
    'CvDraftSerializer',
    'CvDraftWriteSerializer',
    'CvExportCreateSerializer',
    'CvExportSerializer',
    'CvSharedLinkCreateSerializer',
    'CvSharedLinkSerializer',
    'CvSkillSerializer',
    'CvTemplateSwitchSerializer',
    'CvV2CreateSerializer',
    'CvV2DuplicateSerializer',
    'CvV2ImportSerializer',
    'CvV2MetadataUpdateSerializer',
    'CvV2Serializer',
    'CvVersionSerializer',
    'CvVersionSummarySerializer',
    'SharedCvVersionSerializer',
    'UserCvSerializer',
]
