import { Button, Modal, Slider } from 'antd'
import { useState } from 'react'
import { getRegionLabel } from '../../model/region-labels'
import LayoutResizeControls from '../LayoutResizeControls'

export default function LayoutPanel({ regions, capabilities, onResize, sections, pageMargin, onPageMarginChange }) {
  const [guide, setGuide] = useState(false)
  return <div className="space-y-4"><Button onClick={() => setGuide(true)}>Xem hướng dẫn tùy chỉnh bố cục</Button>{onPageMarginChange && <section className="rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-bold text-slate-700">Lề trang</p><p className="text-xs text-slate-500">Giảm lề để tận dụng diện tích A4.</p></div><span className="text-sm font-bold text-slate-700">{pageMargin} mm</span></div><Slider aria-label="Lề trang CV" min={5} max={16} value={pageMargin} onChange={onPageMarginChange} /></section>}<div className="space-y-2">{regions.map((region) => <div key={region.id} className="rounded-lg border border-slate-200 bg-slate-50 p-3"><div className="mb-2 flex justify-between text-xs font-bold uppercase"><span>{getRegionLabel(region.id)}</span><span>{region.width_percent}%</span></div><div className="space-y-1">{region.section_instance_ids.map((id) => <div key={id} className="rounded bg-white px-2 py-1 text-sm shadow-sm">{sections.find(({ section }) => section.instance_id === id)?.section.title || id}</div>)}</div></div>)}</div><LayoutResizeControls regions={regions} capabilities={capabilities} onResize={onResize} /><Modal open={guide} footer={null} onCancel={() => setGuide(false)} title="Hướng dẫn tùy chỉnh bố cục"><p className="font-semibold">Với tính năng Tùy chỉnh bố cục, bạn có thể:</p><ol className="mt-3 list-decimal space-y-2 pl-5"><li>Điều chỉnh độ rộng một cột trong CV</li><li>Điều chỉnh lề A4 để tối ưu không gian</li><li>Di chuyển vị trí một mục</li></ol></Modal></div>
}
