export const ADMIN_ROUTES = [
  {
    id: 'dashboard',
    segment: '/dashboard',
    lazyKey: 'AdminDashboardPage',
    title: 'Bảng điều khiển',
    navLabel: 'Tổng quan',
    iconKey: 'dashboard',
    permission: 'dashboard.view',
    showInNav: true,
  },
  {
    id: 'companies',
    segment: '/companies',
    lazyKey: 'AdminCompaniesPage',
    title: 'Danh sách công ty',
    navLabel: 'Công ty',
    iconKey: 'companies',
    permissionsAny: ['company.view', 'company_update.view'],
    showInNav: true,
  },
  {
    id: 'companyDetail',
    segment: '/companies/:publicId',
    lazyKey: 'AdminCompanyDetailPage',
    title: 'Chi tiết công ty',
    permission: 'company.view',
    showInNav: false,
  },
  {
    id: 'cvCatalogue',
    segment: '/cv-catalogue',
    lazyKey: 'AdminCvCataloguePage',
    title: 'Catalogue CV',
    navLabel: 'Catalogue CV',
    iconKey: 'cv',
    permission: 'cv_template.view',
    showInNav: true,
  },
  {
    id: 'services',
    segment: '/services',
    lazyKey: 'AdminEmployerServicesPage',
    title: 'Dịch vụ nhà tuyển dụng',
    navLabel: 'Dịch vụ NTD',
    iconKey: 'services',
    permission: 'service_catalog.view',
    showInNav: true,
  },
  {
    id: 'consultationLeads',
    segment: '/consultation-leads',
    lazyKey: 'AdminConsultationLeadsPage',
    title: 'Khách hàng tư vấn',
    navLabel: 'Lead tư vấn',
    iconKey: 'leads',
    permission: 'consultation_lead.view',
    showInNav: true,
  },
  {
    id: 'jobModeration',
    segment: '/job-moderation',
    lazyKey: 'AdminJobModerationPage',
    title: 'Duyệt tin tuyển dụng',
    navLabel: 'Duyệt tin tuyển dụng',
    iconKey: 'moderation',
    permission: 'job_moderation.view',
    showInNav: true,
  },
  {
    id: 'blog',
    segment: '/blog',
    lazyKey: 'AdminBlogManagementPage',
    title: 'Cẩm nang nghề nghiệp',
    navLabel: 'Bài viết',
    iconKey: 'blog',
    permission: 'blog.view',
    showInNav: true,
  },
  {
    id: 'blogNew',
    segment: '/blog/new',
    lazyKey: 'AdminBlogNewPage',
    title: 'Tạo bài viết',
    permissionsAll: ['blog.view', 'blog.manage'],
    showInNav: false,
  },
  {
    id: 'blogEdit',
    segment: '/blog/:publicId/edit',
    lazyKey: 'AdminBlogEditPage',
    title: 'Biên tập bài viết',
    permission: 'blog.view',
    showInNav: false,
  },
  {
    id: 'accounts',
    segment: '/accounts',
    lazyKey: 'AdminAccountsPage',
    title: 'Quản lý tài khoản',
    navLabel: 'Tài khoản',
    iconKey: 'accounts',
    permissionsAny: [
      'account.view',
      'account.admin.view',
      'account.admin.invite',
    ],
    showInNav: true,
  },
  {
    id: 'recruiters',
    segment: '/recruiters',
    lazyKey: 'AdminRecruitersPage',
    title: 'Nhà tuyển dụng',
    navLabel: 'Nhà tuyển dụng',
    iconKey: 'accounts',
    permissionsAny: [
      'account.employer.view',
      'account.view',
      'employer_verification.view',
    ],
    showInNav: true,
  },
  {
    id: 'accountDetail',
    segment: '/accounts/:publicId',
    lazyKey: 'AdminAccountDetailPage',
    title: 'Chi tiết tài khoản',
    permissionsAny: [
      'account.view',
      'account.employer.view',
      'account.admin.view',
      'account.admin.invite',
      'employer_verification.view',
      'company_update.view',
    ],
    showInNav: false,
  },
  {
    id: 'accessControl',
    segment: '/access-control',
    lazyKey: 'AdminAccessControlPage',
    title: 'Phân quyền quản trị',
    navLabel: 'Phân quyền',
    iconKey: 'shield',
    permission: 'admin_access.view',
    showInNav: true,
  },
  {
    id: 'settings',
    segment: '/settings',
    lazyKey: 'AdminSettingsPage',
    title: 'Cài đặt hệ thống',
    navLabel: 'Cài đặt hệ thống',
    iconKey: 'settings',
    permission: 'site_setting.view',
    requireSuperuser: true,
    showInNav: true,
  },
  {
    id: 'account',
    segment: '/account',
    lazyKey: 'AdminAccountPage',
    title: 'Cài đặt tài khoản',
    navLabel: 'Tài khoản của tôi',
    iconKey: 'account',
    permission: null,
    showInNav: true,
  },
  {
    id: 'accessDenied',
    segment: '/access-denied',
    lazyKey: 'AdminAccessDeniedPage',
    title: 'Không có quyền truy cập',
    permission: null,
    showInNav: false,
  },
]
