"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


ENVIRONMENT = config('ENVIRONMENT', default='development').strip().lower()
IS_PRODUCTION = ENVIRONMENT == 'production'
_DEFAULT_SECRET_KEY = 'django-insecure-dev-key-change-me-at-least-32-characters'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=_DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

RECAPTCHA_SECRET_KEY = config('RECAPTCHA_SECRET_KEY', default='')
RECAPTCHA_SCORE_THRESHOLD = config('RECAPTCHA_SCORE_THRESHOLD', default=0.5, cast=float)

if IS_PRODUCTION:
    if DEBUG:
        raise ImproperlyConfigured('DEBUG phải là False khi ENVIRONMENT=production.')
    if SECRET_KEY == _DEFAULT_SECRET_KEY:
        raise ImproperlyConfigured('SECRET_KEY production phải được cấu hình qua biến môi trường.')
    if set(ALLOWED_HOSTS).issubset({'localhost', '127.0.0.1'}):
        raise ImproperlyConfigured('ALLOWED_HOSTS production phải chứa domain hợp lệ.')
    if not RECAPTCHA_SECRET_KEY:
        raise ImproperlyConfigured('RECAPTCHA_SECRET_KEY là bắt buộc ở production.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'corsheaders',
    # Local apps
    'apps.accounts',
    'apps.skills',
    'apps.candidates',
    'apps.employers',
    'apps.locations',
    'apps.cv_templates',
    'apps.cvs',
    'apps.jobs',
    'apps.applications',
    'apps.interviews',
    'apps.ai_core',
    'apps.dashboard',
    'apps.sitecontent',
    'apps.blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'common.security.ApiSecurityHeadersMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='ai_career_coach'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 6},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded CVs, template thumbnails)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_PUBLIC_BASE_URL = config('MEDIA_PUBLIC_BASE_URL', default='')
IMAGE_UPLOAD_MAX_SIZE = config('IMAGE_UPLOAD_MAX_SIZE', default=5 * 1024 * 1024, cast=int)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.accounts.authentication.AccountJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'common.pagination.StandardPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'two_factor': '5/min',
        'two_factor_verify': '10/min',
        'register': '5/min',
        'verify_email': '5/min',
        'password_reset': '5/min',
        # Bucket riêng cho bước confirm: gõ sai mật khẩu mới vài lần không được
        # phép khoá luôn việc xin link (và ngược lại) — chung IP, chung quota.
        'password_reset_confirm': '10/min',
        'oauth': '10/min',
        'feedback': '5/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=config('JWT_ACCESS_TOKEN_MINUTES', default=15, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=config('JWT_REFRESH_TOKEN_DAYS', default=7, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    # `or` để dòng .env bỏ trống (JWT_SIGNING_KEY=) vẫn rơi về SECRET_KEY: chuỗi
    # rỗng làm PyJWT ném InvalidKeyError ở mọi lần phát token. Production vẫn bị
    # ép phải khai báo key riêng ở khối kiểm tra IS_PRODUCTION bên dưới.
    'SIGNING_KEY': config('JWT_SIGNING_KEY', default='') or SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# drf-spectacular (OpenAPI 3 schema + Swagger UI / ReDoc)
SPECTACULAR_SETTINGS = {
    'TITLE': 'ProCV API',
    'DESCRIPTION': (
        'API cho nền tảng ProCV — CV Builder, phân tích CV, '
        'so khớp CV–Job và tuyển dụng. Dùng JWT: đăng nhập lấy access token '
        'rồi bấm "Authorize" và nhập "Bearer <access_token>".'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
    },
    # Đặt tên enum tường minh để tránh trùng tên tự sinh (status/level dùng ở nhiều bảng)
    'ENUM_NAME_OVERRIDES': {
        'JobStatusEnum': 'apps.jobs.models.Job.Status',
        'ApplicationStatusEnum': 'apps.applications.models.Application.Status',
        # CvSkill.Level và JobSkill.MinLevel cùng tập beginner/intermediate/advanced -> 1 enum chung
        'SkillLevelEnum': 'apps.jobs.models.JobSkill.MinLevel',
        'LocationLevelEnum': 'apps.locations.models.Location.Level',
    },
    'TAGS': [
        {'name': 'auth', 'description': 'Đăng ký, đăng nhập, JWT, tài khoản hiện tại'},
        {'name': 'candidate', 'description': 'Hồ sơ ứng viên'},
        {'name': 'employer', 'description': 'Hồ sơ công ty / nhà tuyển dụng'},
        {'name': 'cvs', 'description': 'CV Builder + upload CV'},
        {'name': 'cv-templates', 'description': 'Mẫu CV'},
        {'name': 'jobs', 'description': 'Tin tuyển dụng, danh mục ngành nghề, thống kê'},
        {'name': 'applications', 'description': 'Ứng tuyển & quản lý hồ sơ ứng tuyển'},
        {'name': 'locations', 'description': 'Tra cứu địa điểm (tỉnh/xã)'},
    ],
}

# CORS - frontend dev server (Vite default port)
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173',
    cast=Csv(),
)
CORS_ALLOW_CREDENTIALS = False
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

# SecurityMiddleware protects Django Admin/session cookies as well as API responses.
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=IS_PRODUCTION, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if config(
    'SECURE_PROXY_SSL_HEADER_ENABLED', default=IS_PRODUCTION, cast=bool
) else None
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=IS_PRODUCTION, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=IS_PRODUCTION, cast=bool)
SESSION_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31_536_000 if IS_PRODUCTION else 0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=IS_PRODUCTION, cast=bool)
SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)
X_FRAME_OPTIONS = 'DENY'

if IS_PRODUCTION:
    jwt_signing_key = config('JWT_SIGNING_KEY', default='')
    if not jwt_signing_key:
        raise ImproperlyConfigured('JWT_SIGNING_KEY là bắt buộc khi ENVIRONMENT=production.')
    if len(jwt_signing_key) < 32:
        raise ImproperlyConfigured('JWT_SIGNING_KEY production phải có ít nhất 32 ký tự.')

# Redis cache — lưu token xác thực email + cooldown gửi lại (tự hết hạn theo TTL)
REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/1')
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'},
    }
}

# Celery dùng cùng Redis nhưng queue riêng cho email auth. Chạy worker và beat
# tách process khỏi web server để SMTP không làm chậm request đăng ký/login.
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=REDIS_URL)
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=None)
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_ROUTES = {'apps.accounts.tasks.auth_email.*': {'queue': 'auth-email'}}
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TIME_LIMIT = 60
CELERY_TASK_SOFT_TIME_LIMIT = 50
CELERY_BEAT_SCHEDULE = {
    'dispatch-pending-auth-email-jobs': {
        'task': 'apps.accounts.tasks.auth_email.dispatch_pending_auth_email_jobs',
        'schedule': 60.0,
    },
}

# Email — nhà cung cấp SMTP tuỳ ý (Gmail, SendGrid, Amazon SES, Mailgun, Postmark...).
# Chưa điền EMAIL_HOST_USER -> in ra console cho dev; điền credential vào .env là
# tự chuyển sang gửi thật (không cần đổi thêm gì). EMAIL_TIMEOUT chặn request treo
# khi SMTP chậm/không phản hồi.
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_HOST_USER
    else 'django.core.mail.backends.console.EmailBackend',
)
# Người gửi hiển thị; tên có thể override runtime qua site setting `email_from_name`.
# `or` để dòng .env bỏ trống (EMAIL_FROM_ADDRESS=) vẫn rơi về địa chỉ hợp lệ.
EMAIL_FROM_NAME = config('EMAIL_FROM_NAME', default='') or 'ProCV'
EMAIL_FROM_ADDRESS = config('EMAIL_FROM_ADDRESS', default='') or EMAIL_HOST_USER or 'no-reply@procv.vn'
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='') or f'{EMAIL_FROM_NAME} <{EMAIL_FROM_ADDRESS}>'
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# URL frontend để dựng link xác thực trong email.
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')
EMPLOYER_FRONTEND_URL = config('EMPLOYER_FRONTEND_URL', default=FRONTEND_URL)
EMPLOYER_EMAIL_VERIFICATION_PATH = config(
    'EMPLOYER_EMAIL_VERIFICATION_PATH', default='/tuyendung/app/xac-thuc-email'
)

# Xác thực email: TTL token (24h) và thời gian chờ giữa 2 lần gửi lại (giây).
EMAIL_VERIFICATION_TTL = config('EMAIL_VERIFICATION_TTL', default=60 * 60 * 24, cast=int)
EMAIL_VERIFICATION_RESEND_COOLDOWN = config('EMAIL_VERIFICATION_RESEND_COOLDOWN', default=60, cast=int)

# Đặt lại mật khẩu: TTL ngắn hơn xác thực email (30 phút) vì đây là luồng chiếm
# được tài khoản; cooldown chặn spam gửi lại tới cùng một hòm thư.
PASSWORD_RESET_TTL = config('PASSWORD_RESET_TTL', default=60 * 30, cast=int)
PASSWORD_RESET_RESEND_COOLDOWN = config('PASSWORD_RESET_RESEND_COOLDOWN', default=60, cast=int)

# Xác minh hai bước qua mã email: mã ngắn, chỉ dùng một lần và hết hạn sau 3 phút.
TWO_FACTOR_CODE_TTL = config('TWO_FACTOR_CODE_TTL', default=60 * 3, cast=int)

# Social login (OAuth Authorization Code Flow qua backend callback).
# Chưa điền client id/secret -> nút social báo "chưa cấu hình" (không crash).
OAUTH_GOOGLE_CLIENT_ID = config('OAUTH_GOOGLE_CLIENT_ID', default='')
OAUTH_GOOGLE_CLIENT_SECRET = config('OAUTH_GOOGLE_CLIENT_SECRET', default='')
OAUTH_FACEBOOK_CLIENT_ID = config('OAUTH_FACEBOOK_CLIENT_ID', default='')
OAUTH_FACEBOOK_CLIENT_SECRET = config('OAUTH_FACEBOOK_CLIENT_SECRET', default='')
OAUTH_FACEBOOK_GRAPH_VERSION = config('OAUTH_FACEBOOK_GRAPH_VERSION', default='v21.0')
OAUTH_LINKEDIN_CLIENT_ID = config('OAUTH_LINKEDIN_CLIENT_ID', default='')
OAUTH_LINKEDIN_CLIENT_SECRET = config('OAUTH_LINKEDIN_CLIENT_SECRET', default='')
# Trang callback phía frontend (backend redirect về đây kèm one_time_code hoặc error).
OAUTH_MAIN_CALLBACK_URL = config('OAUTH_MAIN_CALLBACK_URL', default=f'{FRONTEND_URL}/oauth/callback')
OAUTH_EMPLOYER_CALLBACK_URL = config(
    'OAUTH_EMPLOYER_CALLBACK_URL', default=f'{FRONTEND_URL}/tuyendung/app/oauth/callback'
)
OAUTH_STATE_TTL = config('OAUTH_STATE_TTL', default=600, cast=int)       # state chống CSRF: 10 phút
OAUTH_CODE_TTL = config('OAUTH_CODE_TTL', default=60, cast=int)          # one_time_code đổi JWT: 60s

# API docs hữu ích ở local/staging, nhưng không public mặc định ở production.
API_DOCS_ENABLED = config('API_DOCS_ENABLED', default=DEBUG, cast=bool)
