# Generated by Django 5.1.5 on 2026-07-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_remove_employerprofile_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='has_brand_page',
            field=models.BooleanField(default=False, help_text='Bật trang thương hiệu — tin tuyển dụng hiển thị dưới URL /brand/... với header công ty'),
        ),
    ]
