# Generated by Django 5.1.5 on 2026-07-11 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_employerprofile_has_brand_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('business_type', models.CharField(choices=[('enterprise', 'Doanh nghiệp'), ('household', 'Hộ kinh doanh')], default='enterprise', max_length=20)),
                ('tax_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('trade_name_same_as_registered', models.BooleanField(default=False)),
                ('logo_url', models.TextField(blank=True)),
                ('has_no_logo', models.BooleanField(default=False)),
                ('cover_image_url', models.TextField(blank=True)),
                ('website_url', models.TextField(blank=True)),
                ('has_no_website', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('company_size', models.CharField(blank=True, choices=[('1-9', '1 - 9 nhân viên'), ('10-24', '10 - 24 nhân viên'), ('25-99', '25 - 99 nhân viên'), ('100-499', '100 - 499 nhân viên'), ('500-1000', '500 - 1000 nhân viên'), ('1000+', '1000+ nhân viên'), ('3000+', '3000+ nhân viên'), ('5000+', '5000+ nhân viên'), ('10000+', '10000+ nhân viên')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('employee_benefits', models.TextField(blank=True)),
                ('markets', models.JSONField(blank=True, default=list)),
                ('target_customers', models.JSONField(blank=True, default=list)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('has_brand_page', models.BooleanField(default=False, help_text='Bật trang thương hiệu — tin tuyển dụng hiển thị dưới URL /brand/... với header công ty')),
                ('verification_status', models.CharField(choices=[('unverified', 'Chưa xác thực'), ('pending', 'Chờ duyệt'), ('verified', 'Đã xác thực'), ('rejected', 'Bị từ chối')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='employers.company')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_industries', to='employers.company')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employers.industry')),
            ],
            options={
                'verbose_name_plural': 'company industries',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='companies', through='employers.CompanyIndustry', to='employers.industry'),
        ),
        migrations.CreateModel(
            name='CompanyUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('changes', models.JSONField(default=dict)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('proof_type', models.CharField(blank=True, choices=[('business_registration', 'Giấy đăng ký doanh nghiệp hoặc tương đương'), ('authorization_and_id', 'Giấy ủy quyền + giấy tờ định danh')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='employers.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('business_registration', 'Giấy đăng ký doanh nghiệp'), ('trade_name_proof', 'Chứng minh tên thương mại'), ('authorization_letter', 'Giấy ủy quyền'), ('identity_document', 'Giấy tờ định danh (CCCD/hộ chiếu)'), ('data_processing_agreement', 'Thỏa thuận xử lý dữ liệu cá nhân')], max_length=30)),
                ('file_url', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employers.company')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('update_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employers.companyupdaterequest')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('company_role', models.CharField(blank=True, choices=[('owner', 'Người tạo công ty'), ('member', 'Thành viên')], max_length=20)),
                ('membership_status', models.CharField(blank=True, choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], max_length=20)),
                ('membership_proof_type', models.CharField(blank=True, choices=[('business_registration', 'Giấy đăng ký doanh nghiệp hoặc tương đương'), ('authorization_and_id', 'Giấy ủy quyền + giấy tờ định danh')], max_length=30)),
                ('membership_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('membership_review_note', models.TextField(blank=True)),
                ('position_title', models.CharField(blank=True, max_length=255)),
                ('verified_phone', models.CharField(blank=True, max_length=20)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('dpa_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruiters', to='employers.company')),
                ('membership_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='companyindustry',
            constraint=models.UniqueConstraint(fields=('company', 'industry'), name='uniq_company_industry'),
        ),
        migrations.AddConstraint(
            model_name='companyindustry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('company',), name='uniq_company_primary_industry'),
        ),
        migrations.AddConstraint(
            model_name='companyupdaterequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('company',), name='uniq_company_pending_update_request'),
        ),
        migrations.AddIndex(
            model_name='phoneotp',
            index=models.Index(fields=['user', '-created_at'], name='phone_otp_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruiterprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('verified_phone', ''), _negated=True), fields=('verified_phone',), name='uniq_recruiter_verified_phone'),
        ),
    ]
