# Generated by Django 5.1.5 on 2026-07-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_migrate_employer_profiles_to_companies'),
        # jobs phải gỡ FK employer_profile trước khi xóa model.
        ('jobs', '0016_job_company_final'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
    ]
