# Generated by Django 5.2.7 on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('employers', '0009_recruiter_registration_profile'),
        ('jobs', '0019_jobcategorylocalization_locale_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('position_level', models.CharField(choices=[('employee', 'Nhân viên'), ('team_lead', 'Trưởng nhóm'), ('manager', 'Trưởng / Phó phòng'), ('supervisor', 'Quản lý / Giám sát'), ('branch_manager', 'Trưởng chi nhánh'), ('vice_director', 'Phó giám đốc'), ('director', 'Giám đốc'), ('intern', 'Thực tập sinh')], max_length=30)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_continuous', models.BooleanField(default=False)),
                ('headcount', models.PositiveIntegerField(default=1)),
                ('budget_min', models.PositiveBigIntegerField(blank=True, null=True)),
                ('budget_max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('budget_source', models.CharField(choices=[('company', 'Công ty'), ('personal', 'Cá nhân')], max_length=20)),
                ('consultation_topics', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employer_recruitment_needs', to='jobs.jobcategory')),
                ('recruiter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_need', to='employers.recruiterprofile')),
            ],
        ),
    ]
