# Generated by Django 5.2.7 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employers', '0011_allow_duplicate_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocument',
            name='company',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='documents',
                to='employers.company',
            ),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='recruiter',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='personal_documents',
                to='employers.recruiterprofile',
            ),
        ),
        migrations.AddConstraint(
            model_name='companydocument',
            constraint=models.CheckConstraint(
                condition=models.Q(('doc_type', 'data_processing_agreement'), ('company__isnull', False), _connector='OR'),
                name='company_document_requires_company_unless_dpa',
            ),
        ),
    ]
