# Generated by Django 5.2.7 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('employers', '0012_companydocument_recruiter_dpa')]

    operations = [
        migrations.AlterField(
            model_name='recruitmentneed',
            name='recruiter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recruitment_needs',
                to='employers.recruiterprofile',
            ),
        ),
        migrations.AddField(
            model_name='recruitmentneed',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
