# Generated by Django 5.2.1 on 2026-07-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0014_seed_company_industries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='membership_proof_type',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='membership_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='membership_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='membership_review_note',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='membership_status',
        ),
    ]
