# Generated by Django 5.1.5 on 2026-07-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0015_remove_recruiter_membership_review_workflow'),
        ('jobs', '0019_jobcategorylocalization_locale_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position_level', models.CharField(choices=[('employee', 'Nhân viên'), ('team_lead', 'Trưởng nhóm'), ('manager', 'Trưởng / Phó phòng'), ('supervisor', 'Quản lý / Giám sát'), ('branch_manager', 'Trưởng chi nhánh'), ('vice_director', 'Phó giám đốc'), ('director', 'Giám đốc'), ('intern', 'Thực tập sinh')], max_length=30)),
                ('headcount_target', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_continuous', models.BooleanField(default=False)),
                ('budget_min', models.PositiveBigIntegerField(blank=True, null=True)),
                ('budget_max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('budget_source', models.CharField(choices=[('company', 'Công ty'), ('personal', 'Cá nhân')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('active', 'Đang chạy'), ('paused', 'Tạm dừng'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_campaigns', to='employers.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='employers.recruiterprofile')),
                ('position_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_campaigns', to='jobs.jobcategory')),
                ('source_need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='employers.recruitmentneed')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'status', '-created_at'], name='emp_camp_owner_status_idx')],
            },
        ),
    ]
