# Generated by Django 5.1.5 on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0016_recruitmentcampaign'),
        ('jobs', '0020_jobstatushistory_job_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentcampaign',
            name='budget_source',
            field=models.CharField(
                choices=[('company', 'Công ty'), ('personal', 'Cá nhân')],
                default='company',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='recruitmentcampaign',
            name='position_category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recruitment_campaigns',
                to='jobs.jobcategory',
            ),
        ),
        migrations.AlterField(
            model_name='recruitmentcampaign',
            name='position_level',
            field=models.CharField(
                blank=True,
                choices=[
                    ('employee', 'Nhân viên'),
                    ('team_lead', 'Trưởng nhóm'),
                    ('manager', 'Trưởng / Phó phòng'),
                    ('supervisor', 'Quản lý / Giám sát'),
                    ('branch_manager', 'Trưởng chi nhánh'),
                    ('vice_director', 'Phó giám đốc'),
                    ('director', 'Giám đốc'),
                    ('intern', 'Thực tập sinh'),
                ],
                max_length=30,
            ),
        ),
    ]
