# Generated by Django 5.1.5 on 2026-07-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0017_campaign_quick_create_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentcampaign',
            name='company',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='recruitment_campaigns',
                to='employers.company',
            ),
        ),
    ]
