# Generated by Django 5.1.5 on 2026-08-10 01:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employers', '0036_verification_document_replaced_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUpdateEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('submitted', 'Đã gửi'),
                            ('resubmitted', 'Đã gửi lại'),
                            ('revision_created', 'Đã tạo phiên bản'),
                            ('review_started', 'Bắt đầu thẩm định'),
                            ('document_reviewed', 'Đã xử lý giấy tờ'),
                            ('changes_requested', 'Yêu cầu chỉnh sửa'),
                            ('approved', 'Đã duyệt'),
                            ('rejected', 'Đã từ chối'),
                            ('withdrawn', 'Đã rút'),
                            ('cancelled', 'Đã hủy'),
                        ],
                        max_length=32,
                    ),
                ),
                ('revision_number', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUpdateRevision',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('number', models.PositiveIntegerField()),
                ('changes', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                (
                    'proof_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('business_registration', 'Giấy đăng ký doanh nghiệp hoặc tương đương'),
                            ('authorization_and_id', 'Giấy ủy quyền + giấy tờ định danh'),
                        ],
                        max_length=30,
                    ),
                ),
                ('base_company_updated_at', models.DateTimeField()),
                ('base_values', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='companyupdaterequest',
            name='uniq_co_requester_pending_upd',
        ),
        migrations.AddField(
            model_name='companyupdaterequest',
            name='base_company_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyupdaterequest',
            name='base_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='companyupdaterequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Chờ duyệt'),
                    ('submitted', 'Đã gửi'),
                    ('in_review', 'Đang thẩm định'),
                    ('changes_requested', 'Cần chỉnh sửa'),
                    ('approved', 'Đã duyệt'),
                    ('rejected', 'Từ chối'),
                    ('withdrawn', 'Đã rút'),
                    ('cancelled', 'Đã hủy'),
                ],
                default='submitted',
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name='companyupdaterequest',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('status__in', ['pending', 'submitted', 'in_review', 'changes_requested'])
                ),
                fields=('company', 'requested_by'),
                name='uniq_co_requester_pending_upd',
            ),
        ),
        migrations.AddField(
            model_name='companyupdateevent',
            name='actor',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='companyupdateevent',
            name='update_request',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='events',
                to='employers.companyupdaterequest',
            ),
        ),
        migrations.AddField(
            model_name='companyupdaterevision',
            name='documents',
            field=models.ManyToManyField(
                blank=True, related_name='company_update_revisions', to='employers.companydocument'
            ),
        ),
        migrations.AddField(
            model_name='companyupdaterevision',
            name='media_uploads',
            field=models.ManyToManyField(
                blank=True,
                related_name='company_update_revisions',
                to='employers.companymediaupload',
            ),
        ),
        migrations.AddField(
            model_name='companyupdaterevision',
            name='submitted_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='companyupdaterevision',
            name='update_request',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='revisions',
                to='employers.companyupdaterequest',
            ),
        ),
        migrations.AddField(
            model_name='companyupdaterequest',
            name='current_revision',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='employers.companyupdaterevision',
            ),
        ),
        migrations.AddField(
            model_name='companydocument',
            name='update_revision',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='attached_documents',
                to='employers.companyupdaterevision',
            ),
        ),
        migrations.AddField(
            model_name='companymediaupload',
            name='update_revision',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='attached_media_uploads',
                to='employers.companyupdaterevision',
            ),
        ),
        migrations.AddIndex(
            model_name='companyupdateevent',
            index=models.Index(
                fields=['update_request', 'created_at'], name='emp_co_update_event_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='companyupdaterevision',
            constraint=models.UniqueConstraint(
                fields=('update_request', 'number'), name='uniq_company_update_revision_number'
            ),
        ),
    ]
