# Generated by Django 5.1.5 on 2026-08-10 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employers', '0041_employer_company_link_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerActivity',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('verification_approved', 'Hồ sơ xác thực đã được duyệt'),
                            ('verification_changes_requested', 'Hồ sơ xác thực cần bổ sung'),
                            ('verification_rejected', 'Hồ sơ xác thực bị từ chối'),
                            ('verification_revoked', 'Xác thực đã bị thu hồi'),
                            ('verification_expired', 'Xác thực đã hết hiệu lực'),
                            ('document_changes_requested', 'Giấy tờ xác thực cần bổ sung'),
                            ('document_rejected', 'Giấy tờ xác thực bị từ chối'),
                            ('company_link_removed', 'Liên kết công ty đã được gỡ'),
                        ],
                        max_length=48,
                    ),
                ),
                ('dedupe_key', models.CharField(max_length=160)),
                ('summary', models.CharField(max_length=240)),
                ('subject_public_id', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployerNotification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                (
                    'event_type',
                    models.CharField(
                        choices=[
                            ('verification_approved', 'Hồ sơ xác thực đã được duyệt'),
                            ('verification_changes_requested', 'Hồ sơ xác thực cần bổ sung'),
                            ('verification_rejected', 'Hồ sơ xác thực bị từ chối'),
                            ('verification_revoked', 'Xác thực đã bị thu hồi'),
                            ('verification_expired', 'Xác thực đã hết hiệu lực'),
                            ('document_changes_requested', 'Giấy tờ xác thực cần bổ sung'),
                            ('document_rejected', 'Giấy tờ xác thực bị từ chối'),
                            ('company_link_removed', 'Liên kết công ty đã được gỡ'),
                        ],
                        max_length=48,
                    ),
                ),
                ('dedupe_key', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True)),
                ('action_path', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployerNotificationPreference',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('intermediate_verification_email', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='employerverificationnotification',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddConstraint(
            model_name='employerverificationnotification',
            constraint=models.UniqueConstraint(
                condition=models.Q(('dedupe_key__isnull', False)),
                fields=('recipient', 'dedupe_key'),
                name='uniq_emp_verify_notice_dedupe',
            ),
        ),
        migrations.AddField(
            model_name='employeractivity',
            name='actor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='employeractivity',
            name='recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='employer_activities',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='employernotification',
            name='recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='employer_notifications',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='employernotificationpreference',
            name='recipient',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='employer_notification_preference',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name='employeractivity',
            index=models.Index(
                fields=['recipient', '-occurred_at'], name='emp_activity_user_time_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='employeractivity',
            constraint=models.UniqueConstraint(
                fields=('recipient', 'dedupe_key'), name='uniq_employer_activity_recipient_dedupe'
            ),
        ),
        migrations.AddIndex(
            model_name='employernotification',
            index=models.Index(
                fields=['recipient', 'read_at', '-created_at'], name='emp_notice_unread_time_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='employernotification',
            constraint=models.UniqueConstraint(
                fields=('recipient', 'dedupe_key'), name='uniq_employer_notice_recipient_dedupe'
            ),
        ),
    ]
