# Generated by Django 5.1.5 on 2026-08-13 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_employer_domain_permissions'),
        ('employers', '0044_remove_company_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDomainClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('domain', models.CharField(max_length=253)),
                ('method', models.CharField(choices=[('dns_txt', 'DNS TXT'), ('admin_manual', 'Quản trị duyệt thủ công'), ('legacy_inferred', 'Suy luận từ dữ liệu cũ')], default='dns_txt', max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác minh'), ('verified', 'Đã xác minh'), ('grace', 'Thời gian gia hạn'), ('rejected', 'Bị từ chối'), ('revoked', 'Đã thu hồi'), ('expired', 'Hết hiệu lực'), ('legacy_inferred', 'Chưa xác minh (dữ liệu cũ)')], default='pending', max_length=24)),
                ('token_hash', models.CharField(blank=True, max_length=64)),
                ('challenge_expires_at', models.DateTimeField(blank=True, null=True)),
                ('manual_review_requested_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(blank=True, null=True)),
                ('grace_expires_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('review_reason', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_claims', to='employers.company')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_domain_claims_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_domain_claims_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDomainClaimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('event_type', models.CharField(choices=[('challenge_created', 'Đã tạo challenge'), ('challenge_rotated', 'Đã đổi challenge'), ('dns_check_passed', 'DNS hợp lệ'), ('dns_check_failed', 'DNS chưa hợp lệ'), ('manual_review_requested', 'Đã yêu cầu duyệt thủ công'), ('manual_approved', 'Đã duyệt thủ công'), ('manual_rejected', 'Đã từ chối thủ công'), ('grace_started', 'Bắt đầu thời gian gia hạn'), ('reverified', 'Đã xác minh lại'), ('revoked', 'Đã thu hồi'), ('expired', 'Đã hết hiệu lực')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='employers.companydomainclaim')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='companydomainclaim',
            index=models.Index(fields=['company', 'status'], name='emp_domain_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companydomainclaim',
            index=models.Index(fields=['status', 'next_check_at'], name='emp_domain_recheck_idx'),
        ),
        migrations.AddConstraint(
            model_name='companydomainclaim',
            constraint=models.UniqueConstraint(fields=('company', 'domain'), name='uniq_company_domain_claim'),
        ),
        migrations.AddConstraint(
            model_name='companydomainclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['verified', 'grace'])), fields=('domain',), name='uniq_active_verified_company_domain'),
        ),
        migrations.AddIndex(
            model_name='companydomainclaimevent',
            index=models.Index(fields=['claim', '-created_at'], name='emp_domain_event_time_idx'),
        ),
    ]
