# Generated by Django 5.1.5 on 2026-07-12 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0016_job_company_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, help_text='Dùng cho URL /blog/danh-muc/<slug> và SEO', max_length=160, unique=True)),
                ('description', models.CharField(blank=True, help_text='Mô tả ngắn, dùng cho meta description trang danh mục', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Thứ tự trên thanh danh mục ngang')),
                ('is_active', models.BooleanField(default=True, help_text='Tắt danh mục mà không xóa bài')),
                ('seo_title', models.CharField(blank=True, help_text='Ghi đè title tag nếu cần', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục bài viết',
                'verbose_name_plural': 'Danh mục bài viết',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Thẻ bài viết',
                'verbose_name_plural': 'Thẻ bài viết',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL /blog/<slug>; auto từ tiêu đề, sửa tay được để tối ưu SEO', max_length=255, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Sapo/mô tả ngắn: card danh sách + meta description', max_length=500)),
                ('thumbnail_url', models.TextField(blank=True, help_text='Storage key nội bộ hoặc URL ngoài; API tự resolve thành URL public')),
                ('content', models.TextField(help_text='Nội dung HTML từ rich-text editor')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ duyệt'), ('published', 'Đã xuất bản'), ('archived', 'Đã gỡ')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Ngày đăng hiển thị; set lần đầu khi xuất bản', null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, help_text='Ghi đè title tag', max_length=200)),
                ('seo_description', models.CharField(blank=True, help_text='Ghi đè meta description (mặc định dùng summary)', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, help_text='Nhân viên soạn bài; giữ bài khi xóa tài khoản', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('related_job_category', models.ForeignKey(blank=True, help_text='Nguồn cho khối "Danh sách việc làm ..." trong bài; để trống thì ẩn khối', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='jobs.jobcategory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.postcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ['-published_at', '-created_at'],
                'permissions': [('can_publish_post', 'Có thể duyệt và xuất bản bài viết')],
            },
        ),
        migrations.CreateModel(
            name='PinnedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('support_docs', 'Tài liệu hỗ trợ tìm việc (sidebar bài viết)')], default='support_docs', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='blog.post')),
            ],
            options={
                'verbose_name': 'Bài viết ghim',
                'verbose_name_plural': 'Bài viết ghim',
                'ordering': ['placement', 'order'],
                'constraints': [models.UniqueConstraint(fields=('placement', 'post'), name='uq_blog_pinned_placement_post')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-published_at'], name='blog_post_status_615533_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'status', '-published_at'], name='blog_post_category_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'pending', 'published', 'archived'])), name='chk_blog_post_status'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='chk_blog_post_published_at'),
        ),
    ]
