# Generated by Django 5.1.5 on 2026-07-18 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Định danh dùng trong URL/anchor, vd: featured-jobs', unique=True)),
                ('name_vi', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('description_vi', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Tên icon antd, vd: ThunderboltOutlined', max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nhóm dịch vụ',
                'verbose_name_plural': 'Nhóm dịch vụ',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('need', models.CharField(choices=[('post_job', 'Đăng tin tuyển dụng'), ('buy_service', 'Tìm hiểu gói dịch vụ'), ('ai_solution', 'Giải pháp AI sàng lọc CV'), ('employer_branding', 'Truyền thông thương hiệu'), ('other', 'Khác')], default='post_job', max_length=30)),
                ('note', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, help_text='Trang khách đang xem lúc gửi', max_length=500)),
                ('status', models.CharField(choices=[('new', 'Mới'), ('contacted', 'Đã liên hệ')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead tư vấn',
                'verbose_name_plural': 'Lead tư vấn',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='services_co_status_9160df_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name_vi', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('tagline_vi', models.CharField(blank=True, help_text='Mô tả 1 dòng dưới tên gói', max_length=255)),
                ('tagline_en', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=0, help_text='Để trống = hiển thị "Liên hệ"', max_digits=12, null=True)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('unit_vi', models.CharField(blank=True, help_text='VD: / tin đăng 30 ngày', max_length=100)),
                ('unit_en', models.CharField(blank=True, max_length=100)),
                ('vat_note_vi', models.CharField(blank=True, default='Giá chưa bao gồm VAT', max_length=100)),
                ('vat_note_en', models.CharField(blank=True, default='Price excludes VAT', max_length=100)),
                ('benefits_vi', models.JSONField(blank=True, default=list, help_text='Danh sách quyền lợi (list chuỗi)')),
                ('benefits_en', models.JSONField(blank=True, default=list)),
                ('badge_vi', models.CharField(blank=True, help_text='Nhãn nổi bật trên card, vd: Bán chạy nhất', max_length=50)),
                ('badge_en', models.CharField(blank=True, max_length=50)),
                ('is_highlight', models.BooleanField(default=False, help_text='Card viền màu thương hiệu')),
                ('cta_type', models.CharField(choices=[('register', 'Đăng ký tài khoản'), ('contact', 'Liên hệ tư vấn')], default='contact', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Gói dịch vụ',
                'verbose_name_plural': 'Gói dịch vụ',
                'ordering': ['category__order', 'order', 'slug'],
            },
        ),
    ]
