# Generated by Django 5.1.5 on 2026-08-12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_supported_capabilities(apps, schema_editor):
    capability_model = apps.get_model('services', 'ServiceCapability')
    capabilities = (
        ('sponsored_placement', 'Vị trí tài trợ', 'placement', 'placement'),
        ('card_tone', 'Màu nền tin tài trợ', 'job', 'presentation'),
        ('urgent_label', 'Nhãn GẤP', 'job', 'label'),
        ('job_refresh', 'Làm mới tin', 'job', 'refresh'),
        ('job_alert', 'Job Alert', 'job', 'alert'),
        ('saved_remarketing', 'Remarketing tin đã lưu', 'job', 'remarketing'),
        ('visibility_extension', 'Gia hạn vòng đời tin', 'job', 'lifecycle'),
    )
    for code, name_vi, scope, effect_type in capabilities:
        capability_model.objects.update_or_create(
            code=code,
            defaults={
                'name_vi': name_vi,
                'scope': scope,
                'effect_type': effect_type,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [('services', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='ServiceCapability',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'code',
                    models.SlugField(
                        choices=[
                            ('sponsored_placement', 'Vị trí tài trợ'),
                            ('card_tone', 'Màu nền tin tài trợ'),
                            ('urgent_label', 'Nhãn GẤP'),
                            ('job_refresh', 'Làm mới tin'),
                            ('job_alert', 'Job Alert'),
                            ('saved_remarketing', 'Remarketing tin đã lưu'),
                            ('visibility_extension', 'Gia hạn vòng đời tin'),
                        ],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ('name_vi', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('description_vi', models.TextField(blank=True)),
                (
                    'scope',
                    models.CharField(
                        choices=[
                            ('job', 'Tin tuyển dụng'),
                            ('company', 'Doanh nghiệp'),
                            ('placement', 'Vị trí hiển thị'),
                        ],
                        default='job',
                        max_length=20,
                    ),
                ),
                (
                    'effect_type',
                    models.CharField(
                        choices=[
                            ('placement', 'Phân phối tài trợ'),
                            ('presentation', 'Trình bày tin'),
                            ('label', 'Nhãn ngữ nghĩa'),
                            ('refresh', 'Làm mới'),
                            ('alert', 'Thông báo việc làm'),
                            ('remarketing', 'Remarketing'),
                            ('lifecycle', 'Vòng đời tin'),
                        ],
                        max_length=20,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quyền lợi dịch vụ',
                'verbose_name_plural': 'Quyền lợi dịch vụ',
                'ordering': ['code'],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(
                            code__in=(
                                'sponsored_placement',
                                'card_tone',
                                'urgent_label',
                                'job_refresh',
                                'job_alert',
                                'saved_remarketing',
                                'visibility_extension',
                            )
                        ),
                        name='services_capability_supported_code',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='ServicePackageVersion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'version_number',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', 'Bản nháp'),
                            ('published', 'Đang phát hành'),
                            ('archived', 'Đã lưu trữ'),
                        ],
                        default='draft',
                        max_length=20,
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        default='VND',
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[A-Z]{3}$',
                                'Mã tiền tệ phải gồm 3 chữ cái in hoa.',
                            )
                        ],
                    ),
                ),
                (
                    'activate_within_days',
                    models.PositiveSmallIntegerField(
                        default=90,
                        help_text=(
                            'Số ngày khách hàng được phép bắt đầu sử dụng sau khi được cấp lượt.'
                        ),
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3650),
                        ],
                    ),
                ),
                ('terms_vi', models.TextField(blank=True)),
                ('terms_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                (
                    'package',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='versions',
                        to='services.servicepackage',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Phiên bản gói dịch vụ',
                'verbose_name_plural': 'Phiên bản gói dịch vụ',
                'ordering': ['package_id', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackageVersionItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'quantity',
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    'duration_days',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text='Để trống với quyền lợi tức thời như một lượt làm mới.',
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3650),
                        ],
                    ),
                ),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                (
                    'capability',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='version_items',
                        to='services.servicecapability',
                    ),
                ),
                (
                    'package_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='services.servicepackageversion',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Quyền lợi trong phiên bản gói',
                'verbose_name_plural': 'Quyền lợi trong phiên bản gói',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='servicepackageversion',
            constraint=models.UniqueConstraint(
                fields=('package', 'version_number'),
                name='services_package_version_unique_number',
            ),
        ),
        migrations.AddConstraint(
            model_name='servicepackageversion',
            constraint=models.UniqueConstraint(
                condition=models.Q(status='published'),
                fields=('package',),
                name='services_package_one_published_version',
            ),
        ),
        migrations.AddConstraint(
            model_name='servicepackageversion',
            constraint=models.CheckConstraint(
                condition=models.Q(price__gte=0),
                name='services_package_version_nonnegative_price',
            ),
        ),
        migrations.AddConstraint(
            model_name='servicepackageversion',
            constraint=models.CheckConstraint(
                condition=models.Q(activate_within_days__gte=1),
                name='services_package_version_positive_activation_window',
            ),
        ),
        migrations.AddConstraint(
            model_name='servicepackageversionitem',
            constraint=models.UniqueConstraint(
                fields=('package_version', 'capability'),
                name='services_package_version_unique_capability',
            ),
        ),
        migrations.AddConstraint(
            model_name='servicepackageversionitem',
            constraint=models.CheckConstraint(
                condition=models.Q(quantity__gte=1),
                name='services_package_item_positive_quantity',
            ),
        ),
        migrations.AddConstraint(
            model_name='servicepackageversionitem',
            constraint=models.CheckConstraint(
                condition=models.Q(duration_days__isnull=True)
                | models.Q(duration_days__gte=1),
                name='services_package_item_positive_duration',
            ),
        ),
        migrations.RunPython(seed_supported_capabilities, migrations.RunPython.noop),
    ]
