# Generated by Django 5.1.5 on 2026-08-12 15:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0044_remove_company_verification'),
        ('jobs', '0043_job_application_reasons'),
        ('services', '0002_commercial_catalog_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobServiceActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Đang chạy'), ('expired', 'Đã kết thúc'), ('terminated', 'Đã dừng')], default='active', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('snapshot', models.JSONField(default=dict)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_service_activations', to='employers.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_job_service_activations', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_activations', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Lượt kích hoạt dịch vụ tin',
                'verbose_name_plural': 'Lượt kích hoạt dịch vụ tin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEntitlementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Chưa sử dụng'), ('consumed', 'Đã sử dụng'), ('expired', 'Hết hạn kích hoạt'), ('revoked', 'Đã thu hồi')], default='available', max_length=20)),
                ('source', models.CharField(choices=[('manual_grant', 'Cấp thủ công'), ('order', 'Đơn hàng'), ('compensation', 'Bù dịch vụ'), ('legacy', 'Chuyển đổi legacy')], max_length=24)),
                ('grant_key', models.CharField(max_length=100)),
                ('unit_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('snapshot', models.JSONField(default=dict)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activate_by', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_entitlement_units', to='employers.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_entitlement_units', to=settings.AUTH_USER_MODEL)),
                ('package_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_units', to='services.servicepackageversion')),
            ],
            options={
                'verbose_name': 'Lượt dịch vụ',
                'verbose_name_plural': 'Lượt dịch vụ',
                'ordering': ['activate_by', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('event_type', models.CharField(choices=[('package_published', 'Phát hành phiên bản gói'), ('unit_granted', 'Cấp lượt'), ('unit_revoked', 'Thu hồi lượt'), ('unit_expired', 'Lượt hết hạn kích hoạt'), ('unit_consumed', 'Sử dụng lượt'), ('activation_created', 'Kích hoạt dịch vụ'), ('activation_expired', 'Dịch vụ kết thúc')], max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('activation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='services.jobserviceactivation')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_audit_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_audit_events', to='employers.company')),
                ('package_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='services.servicepackageversion')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='services.serviceentitlementunit')),
            ],
            options={
                'verbose_name': 'Sự kiện kiểm toán dịch vụ',
                'verbose_name_plural': 'Sự kiện kiểm toán dịch vụ',
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='jobserviceactivation',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='activation', to='services.serviceentitlementunit'),
        ),
        migrations.CreateModel(
            name='JobServiceActivationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('remaining_quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('configuration', models.JSONField(default=dict)),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='services.jobserviceactivation')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activation_items', to='services.servicecapability')),
            ],
            options={
                'verbose_name': 'Quyền lợi đã kích hoạt',
                'verbose_name_plural': 'Quyền lợi đã kích hoạt',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('activation', 'capability'), name='services_activation_unique_capability'), models.CheckConstraint(condition=models.Q(('remaining_quantity__lte', models.F('total_quantity'))), name='services_activation_item_remaining_lte_total'), models.CheckConstraint(condition=models.Q(('ends_at__gte', models.F('starts_at'))), name='services_activation_item_valid_window')],
            },
        ),
        migrations.AddIndex(
            model_name='serviceentitlementunit',
            index=models.Index(fields=['company', 'status', 'activate_by'], name='services_unit_inventory_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceentitlementunit',
            index=models.Index(fields=['status', 'activate_by'], name='services_unit_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceentitlementunit',
            constraint=models.UniqueConstraint(fields=('company', 'grant_key', 'unit_number'), name='services_unit_unique_grant_number'),
        ),
        migrations.AddConstraint(
            model_name='serviceentitlementunit',
            constraint=models.CheckConstraint(condition=models.Q(('activate_by__gte', models.F('granted_at'))), name='services_unit_valid_activation_window'),
        ),
        migrations.AddConstraint(
            model_name='serviceentitlementunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('consumed_at__isnull', False), ('status', 'consumed')), models.Q(models.Q(('status', 'consumed'), _negated=True), ('consumed_at__isnull', True)), _connector='OR'), name='services_unit_consumed_timestamp_state'),
        ),
        migrations.AddConstraint(
            model_name='serviceentitlementunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expired_at__isnull', False), ('status', 'expired')), models.Q(models.Q(('status', 'expired'), _negated=True), ('expired_at__isnull', True)), _connector='OR'), name='services_unit_expired_timestamp_state'),
        ),
        migrations.AddConstraint(
            model_name='serviceentitlementunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revoked_at__isnull', False), ('status', 'revoked')), models.Q(models.Q(('status', 'revoked'), _negated=True), ('revoked_at__isnull', True)), _connector='OR'), name='services_unit_revoked_timestamp_state'),
        ),
        migrations.AddIndex(
            model_name='serviceauditevent',
            index=models.Index(fields=['company', 'occurred_at'], name='services_audit_company_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceauditevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='services_audit_type_idx'),
        ),
        migrations.AddIndex(
            model_name='jobserviceactivation',
            index=models.Index(fields=['job', 'status', 'ends_at'], name='services_job_active_idx'),
        ),
        migrations.AddIndex(
            model_name='jobserviceactivation',
            index=models.Index(fields=['company', 'status', 'ends_at'], name='services_company_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobserviceactivation',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='services_activation_company_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='jobserviceactivation',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gte', models.F('starts_at'))), name='services_activation_valid_window'),
        ),
    ]
