# Generated by Django 5.1.5 on 2026-08-12 17:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0044_remove_company_verification'),
        ('jobs', '0043_job_application_reasons'),
        ('services', '0003_entitlement_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobserviceactivationitem',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='serviceauditevent',
            name='event_type',
            field=models.CharField(choices=[('package_published', 'Phát hành phiên bản gói'), ('unit_granted', 'Cấp lượt'), ('unit_revoked', 'Thu hồi lượt'), ('unit_expired', 'Lượt hết hạn kích hoạt'), ('unit_consumed', 'Sử dụng lượt'), ('activation_created', 'Kích hoạt dịch vụ'), ('activation_expired', 'Dịch vụ kết thúc'), ('capability_used', 'Sử dụng quyền lợi')], max_length=32),
        ),
        migrations.CreateModel(
            name='JobServiceUsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('event_type', models.CharField(choices=[('refresh', 'Làm mới tin'), ('job_alert', 'Gửi Job Alert')], max_length=20)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='services.jobserviceactivation')),
                ('activation_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='services.jobserviceactivationitem')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_service_usage_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_service_usage_events', to='employers.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_usage_events', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Lần sử dụng quyền lợi',
                'verbose_name_plural': 'Lần sử dụng quyền lợi',
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['activation', 'event_type', 'occurred_at'], name='services_usage_activation_idx'), models.Index(fields=['job', 'event_type', 'occurred_at'], name='services_usage_job_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'idempotency_key'), name='services_usage_company_idempotency')],
            },
        ),
    ]
