# Generated by Django 5.1.5 on 2026-08-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_job_service_usage_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPromotionMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impression_count', models.PositiveBigIntegerField(default=0)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('save_count', models.PositiveBigIntegerField(default=0)),
                ('apply_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_metrics', to='services.jobserviceactivation')),
            ],
            options={
                'verbose_name': 'Số liệu dịch vụ tin theo ngày',
                'verbose_name_plural': 'Số liệu dịch vụ tin theo ngày',
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['date'], name='services_promo_metric_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('activation', 'date'), name='services_promo_metric_activation_date')],
            },
        ),
    ]
