# Generated by Django 5.1.5 on 2026-08-12 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employers', '0044_remove_company_verification'),
        ('jobs', '0043_job_application_reasons'),
        ('services', '0005_promotion_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobServiceAlertDispatch',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Đang chuẩn bị'),
                            ('ready', 'Sẵn sàng gửi'),
                            ('sent', 'Đã gửi'),
                            ('empty', 'Không có người nhận phù hợp'),
                            ('cancelled', 'Đã hủy'),
                            ('failed', 'Gửi thất bại'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('selection_cursor', models.PositiveBigIntegerField(default=0)),
                ('selection_finished', models.BooleanField(default=False)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('cancelled_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'activation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='alert_dispatches',
                        to='services.jobserviceactivation',
                    ),
                ),
                (
                    'activation_item',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='alert_dispatches',
                        to='services.jobserviceactivationitem',
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='job_service_alert_dispatches',
                        to='employers.company',
                    ),
                ),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='service_alert_dispatches',
                        to='jobs.job',
                    ),
                ),
                (
                    'usage_event',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='alert_dispatch',
                        to='services.jobserviceusageevent',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Đợt gửi Job Alert',
                'verbose_name_plural': 'Đợt gửi Job Alert',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JobServiceAlertRecipient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_auth_revision', models.PositiveBigIntegerField()),
                ('matched_alert_public_ids', models.JSONField(blank=True, default=list)),
                ('message_id', models.CharField(editable=False, max_length=255, unique=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Đang chờ gửi'),
                            ('sending', 'Đang gửi'),
                            ('sent', 'Đã gửi'),
                            ('cancelled', 'Đã hủy'),
                            ('failed', 'Gửi thất bại'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='service_job_alert_recipients',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'dispatch',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='recipients',
                        to='services.jobservicealertdispatch',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Người nhận Job Alert',
                'verbose_name_plural': 'Người nhận Job Alert',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='jobservicealertdispatch',
            index=models.Index(
                fields=['status', 'selection_finished', 'created_at'],
                name='services_alert_dispatch_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='jobservicealertdispatch',
            index=models.Index(
                fields=['activation', 'created_at'], name='services_alert_activation_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='jobservicealertrecipient',
            index=models.Index(
                fields=['status', 'created_at'], name='services_alert_recipient_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='jobservicealertrecipient',
            index=models.Index(
                fields=['candidate', 'created_at'], name='services_alert_candidate_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='jobservicealertrecipient',
            constraint=models.UniqueConstraint(
                fields=('dispatch', 'candidate'), name='services_alert_dispatch_candidate'
            ),
        ),
    ]
