# Generated by Django 5.1.5 on 2026-08-05 07:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=180)),
                ('article_type', models.CharField(choices=[('FAQ', 'Câu hỏi thường gặp'), ('GUIDE', 'Hướng dẫn')], default='FAQ', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('lifecycle_state', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('ARCHIVED', 'Đã lưu trữ')], default='ACTIVE', max_length=12)),
                ('revision_token', models.PositiveIntegerField(default=1)),
                ('review_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_published_at', models.DateTimeField(blank=True, null=True)),
                ('current_published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category__order', 'order', 'public_id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('IN_REVIEW', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Bị từ chối')], default='DRAFT', max_length=12)),
                ('title', models.CharField(max_length=240)),
                ('body', models.TextField()),
                ('body_plain_text', models.TextField(editable=False)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('source_reference', models.CharField(max_length=500)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('first_published_at', models.DateTimeField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='knowledgebase.knowledgearticle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('first_published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_revisions_first_published', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_revisions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_revisions_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['article_id', '-number'],
            },
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledgebase.knowledgearticlerevision'),
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('review_interval_days', models.PositiveSmallIntegerField(default=180, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(365)])),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('revision_token', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name', 'public_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='chk_kb_cat_order'), models.CheckConstraint(condition=models.Q(('review_interval_days__range', (30, 365))), name='chk_kb_cat_review_days'), models.CheckConstraint(condition=models.Q(('revision_token__gte', 1)), name='chk_kb_cat_revision_token')],
            },
        ),
        migrations.AddField(
            model_name='knowledgearticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='knowledgebase.knowledgecategory'),
        ),
        migrations.CreateModel(
            name='KnowledgeMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('storage_key', models.TextField(unique=True)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('default_alt_text', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_media_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgearticlerevision',
            index=models.Index(fields=['article', '-number'], name='kb_revision_number_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticlerevision',
            index=models.Index(fields=['status', '-updated_at'], name='kb_revision_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticlerevision',
            constraint=models.UniqueConstraint(fields=('article', 'number'), name='uq_kb_revision_article_number'),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticlerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['DRAFT', 'IN_REVIEW'])), fields=('article',), name='uq_kb_revision_open_article'),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticlerevision',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='chk_kb_revision_number'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['category', 'lifecycle_state', 'order'], name='kb_article_public_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['review_due_at'], name='kb_article_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticle',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uq_kb_article_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticle',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='chk_kb_article_order'),
        ),
        migrations.AddConstraint(
            model_name='knowledgearticle',
            constraint=models.CheckConstraint(condition=models.Q(('revision_token__gte', 1)), name='chk_kb_article_revision_token'),
        ),
        migrations.AddIndex(
            model_name='knowledgemediaasset',
            index=models.Index(fields=['-created_at'], name='kb_media_created_idx'),
        ),
    ]
