# Generated by Django 5.1.6 on 2026-08-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('blog', '0004_blog_media_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSpeechAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_revision', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('model_revision', models.CharField(max_length=100)),
                ('voice_id', models.CharField(max_length=64)),
                ('style', models.CharField(max_length=32)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Chờ tạo'),
                            ('ready', 'Sẵn sàng'),
                            ('failed', 'Thất bại'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('asset_url', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='speech_assets',
                        to='blog.post',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='blogspeechasset',
            constraint=models.UniqueConstraint(
                fields=('post', 'post_revision', 'model_revision', 'voice_id', 'style'),
                name='uq_speech_post_rev_voice',
            ),
        ),
        migrations.AddIndex(
            model_name='blogspeechasset',
            index=models.Index(
                fields=['status', 'started_at'],
                name='speech_asset_recovery_idx',
            ),
        ),
    ]
