# Generated by Django 5.1.5 on 2026-08-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speech', '0004_blogspeechasset_finalize_lease_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('surface', models.CharField(choices=[('blog', 'Blog'), ('onboarding', 'Onboarding'), ('chatbot', 'Chatbot'), ('interview', 'Phỏng vấn')], max_length=20)),
                ('session_count', models.PositiveBigIntegerField(default=0)),
                ('generation_count', models.PositiveBigIntegerField(default=0)),
                ('requested_chars', models.PositiveBigIntegerField(default=0)),
                ('cache_hit_count', models.PositiveBigIntegerField(default=0)),
                ('cache_miss_count', models.PositiveBigIntegerField(default=0)),
                ('rejected_count', models.PositiveBigIntegerField(default=0)),
                ('unavailable_count', models.PositiveBigIntegerField(default=0)),
                ('durable_artifact_count', models.PositiveBigIntegerField(default=0)),
                ('durable_artifact_bytes', models.PositiveBigIntegerField(default=0)),
                ('durable_audio_ms', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'surface'],
                'constraints': [models.UniqueConstraint(fields=('date', 'surface'), name='uq_speech_usage_daily_surface')],
            },
        ),
    ]
