from django.urls import path

from .api.views import (
    AdminConsultationLeadDetailView,
    AdminConsultationLeadExportView,
    AdminConsultationLeadListView,
    AdminEntitlementUnitListCreateView,
    AdminEntitlementUnitRevokeView,
    AdminPackageVersionDetailView,
    AdminPackageVersionListCreateView,
    AdminPackageVersionPublishView,
    AdminServiceAuditListView,
    AdminServiceCapabilityListView,
    AdminServiceCategoryDetailView,
    AdminServiceCategoryListCreateView,
    AdminServicePackageDetailView,
    AdminServicePackageListCreateView,
    ConsultationLeadCreateView,
    EmployerActiveServiceListView,
    EmployerServiceActivationCreateView,
    EmployerServiceActivationPreviewView,
    EmployerServiceInventoryView,
    EmployerServiceRefreshView,
    PublicServicePackageListView,
)

urlpatterns = [
    path('packages/', PublicServicePackageListView.as_view(), name='services-packages'),
    path('consultations/', ConsultationLeadCreateView.as_view(), name='services-consultations'),
    path(
        'mine/inventory/',
        EmployerServiceInventoryView.as_view(),
        name='services-employer-inventory',
    ),
    path(
        'activations/preview/',
        EmployerServiceActivationPreviewView.as_view(),
        name='services-employer-activation-preview',
    ),
    path(
        'activations/',
        EmployerServiceActivationCreateView.as_view(),
        name='services-employer-activation-create',
    ),
    path(
        'mine/activations/',
        EmployerActiveServiceListView.as_view(),
        name='services-employer-active-services',
    ),
    path(
        'activations/<str:public_id>/refresh/',
        EmployerServiceRefreshView.as_view(),
        name='services-employer-refresh',
    ),
    path(
        'admin/capabilities/',
        AdminServiceCapabilityListView.as_view(),
        name='services-admin-capabilities',
    ),
    path(
        'admin/package-versions/',
        AdminPackageVersionListCreateView.as_view(),
        name='services-admin-package-versions',
    ),
    path(
        'admin/package-versions/<int:pk>/',
        AdminPackageVersionDetailView.as_view(),
        name='services-admin-package-version-detail',
    ),
    path(
        'admin/package-versions/<int:pk>/publish/',
        AdminPackageVersionPublishView.as_view(),
        name='services-admin-package-version-publish',
    ),
    path(
        'admin/entitlements/',
        AdminEntitlementUnitListCreateView.as_view(),
        name='services-admin-entitlements',
    ),
    path(
        'admin/entitlements/<str:public_id>/revoke/',
        AdminEntitlementUnitRevokeView.as_view(),
        name='services-admin-entitlement-revoke',
    ),
    path(
        'admin/audit/',
        AdminServiceAuditListView.as_view(),
        name='services-admin-audit',
    ),
    path(
        'admin/categories/',
        AdminServiceCategoryListCreateView.as_view(),
        name='services-admin-categories',
    ),
    path(
        'admin/categories/<int:pk>/',
        AdminServiceCategoryDetailView.as_view(),
        name='services-admin-category-detail',
    ),
    path(
        'admin/packages/',
        AdminServicePackageListCreateView.as_view(),
        name='services-admin-packages',
    ),
    path(
        'admin/packages/<int:pk>/',
        AdminServicePackageDetailView.as_view(),
        name='services-admin-package-detail',
    ),
    path(
        'admin/consultations/',
        AdminConsultationLeadListView.as_view(),
        name='services-admin-consultations',
    ),
    path(
        'admin/consultations/export/',
        AdminConsultationLeadExportView.as_view(),
        name='services-admin-consultations-export',
    ),
    path(
        'admin/consultations/<int:pk>/',
        AdminConsultationLeadDetailView.as_view(),
        name='services-admin-consultation-detail',
    ),
]
