"""Account-domain use cases and integrations."""

from .access import is_account_accessible
from .admin_access import (
    assign_membership,
    confirm_department_status_change,
    confirm_membership_assignment,
    confirm_membership_revoke,
    confirm_restore_system_department,
    confirm_restore_system_role,
    confirm_role_permissions_update,
    confirm_role_status_change,
    create_department,
    create_role,
    record_admin_self_action,
    restore_system_department,
    restore_system_role,
    revoke_membership,
    set_department_active,
    set_role_active,
    set_role_permissions,
    sync_permission_catalog,
    update_department,
    update_role,
    update_system_department_metadata,
    update_system_role_metadata,
)
from .captcha import verify_recaptcha, verify_request_captcha
from .verification_delivery import queue_verification_email

__all__ = [
    'assign_membership',
    'confirm_department_status_change',
    'confirm_membership_assignment',
    'confirm_membership_revoke',
    'confirm_restore_system_department',
    'confirm_restore_system_role',
    'confirm_role_permissions_update',
    'confirm_role_status_change',
    'create_department',
    'create_role',
    'is_account_accessible',
    'queue_verification_email',
    'record_admin_self_action',
    'revoke_membership',
    'restore_system_department',
    'restore_system_role',
    'set_department_active',
    'set_role_active',
    'set_role_permissions',
    'sync_permission_catalog',
    'update_department',
    'update_role',
    'update_system_department_metadata',
    'update_system_role_metadata',
    'verify_recaptcha',
    'verify_request_captcha',
]
