# Generated by Django 5.1.5 on 2026-08-09 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('purpose', models.CharField(max_length=64)),
                ('original_filename', models.CharField(max_length=255)),
                ('declared_content_type', models.CharField(max_length=127)),
                ('detected_content_type', models.CharField(blank=True, max_length=127)),
                ('expected_size_bytes', models.PositiveBigIntegerField()),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('uploading', 'Uploading'), ('quarantined', 'Quarantined'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('rejected', 'Rejected'), ('error', 'Error'), ('expired', 'Expired')], default='uploading', max_length=20)),
                ('terminal_reason', models.CharField(blank=True, max_length=64)),
                ('quarantine_storage_key', models.TextField(blank=True)),
                ('upload_lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('upload_lease_until', models.DateTimeField(blank=True, null=True)),
                ('scan_attempts', models.PositiveSmallIntegerField(default=0)),
                ('scan_lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('scan_lease_until', models.DateTimeField(blank=True, null=True)),
                ('next_scan_at', models.DateTimeField(blank=True, null=True)),
                ('scan_result_code', models.CharField(blank=True, max_length=64)),
                ('threat_signature_sha256', models.CharField(blank=True, max_length=64)),
                ('scan_started_at', models.DateTimeField(blank=True, null=True)),
                ('scan_completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('evidence_retained_until', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('quarantine_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('legal_hold_at', models.DateTimeField(blank=True, null=True)),
                ('legal_hold_reason_code', models.CharField(blank=True, max_length=64)),
                ('lock_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upload_sessions',
            },
        ),
        migrations.CreateModel(
            name='UploadScanAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('clean', 'Clean'), ('malicious', 'Malicious'), ('error', 'Error')], default='running', max_length=20)),
                ('result_code', models.CharField(blank=True, max_length=64)),
                ('threat_signature_sha256', models.CharField(blank=True, max_length=64)),
                ('scanner_revision_sha256', models.CharField(blank=True, max_length=64)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_attempt_records', to='uploads.uploadsession')),
            ],
            options={
                'db_table': 'upload_scan_attempts',
                'ordering': ['attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='UploadAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('trust_status', models.CharField(choices=[('clean', 'Clean'), ('legacy_trusted', 'Legacy trusted')], max_length=24)),
                ('purpose', models.CharField(max_length=64)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=127)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('storage_key', models.TextField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_scope', models.CharField(blank=True, max_length=64)),
                ('claim_reference', models.CharField(blank=True, max_length=64)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason_code', models.CharField(blank=True, max_length=64)),
                ('retained_until', models.DateTimeField()),
                ('legal_hold_at', models.DateTimeField(blank=True, null=True)),
                ('legal_hold_reason_code', models.CharField(blank=True, max_length=64)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_assets', to=settings.AUTH_USER_MODEL)),
                ('source_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset', to='uploads.uploadsession')),
            ],
            options={
                'db_table': 'upload_assets',
            },
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['owner', '-created_at'], name='upl_session_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['state', 'next_scan_at'], name='upl_session_scan_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadsession',
            index=models.Index(fields=['state', 'expires_at'], name='upl_session_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('expected_size_bytes__gt', 0)), name='upl_session_expected_size_gt0'),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gte', 0)), name='upl_session_size_gte0'),
        ),
        migrations.AddConstraint(
            model_name='uploadsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('legal_hold_at__isnull', True), ('legal_hold_reason_code', '')), models.Q(('legal_hold_at__isnull', False), models.Q(('legal_hold_reason_code', ''), _negated=True)), _connector='OR'), name='upl_session_hold_complete'),
        ),
        migrations.AddConstraint(
            model_name='uploadscanattempt',
            constraint=models.UniqueConstraint(fields=('session', 'attempt_number'), name='upl_scan_attempt_unique'),
        ),
        migrations.AddConstraint(
            model_name='uploadscanattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'running')), models.Q(models.Q(('status', 'running'), _negated=True), ('completed_at__isnull', False)), _connector='OR'), name='upl_scan_completion_valid'),
        ),
        migrations.AddIndex(
            model_name='uploadasset',
            index=models.Index(fields=['owner', '-created_at'], name='upl_asset_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadasset',
            index=models.Index(fields=['retained_until'], name='upl_asset_retention_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadasset',
            index=models.Index(fields=['claim_scope', 'claim_reference'], name='upl_asset_claim_idx'),
        ),
        migrations.AddConstraint(
            model_name='uploadasset',
            constraint=models.CheckConstraint(condition=models.Q(('size_bytes__gt', 0), models.Q(('deleted_at__isnull', False), ('size_bytes', 0)), _connector='OR'), name='upl_asset_size_or_deleted'),
        ),
        migrations.AddConstraint(
            model_name='uploadasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('claim_reference', ''), ('claim_scope', ''), ('claimed_at__isnull', True)), models.Q(('claimed_at__isnull', False), models.Q(('claim_scope', ''), _negated=True), models.Q(('claim_reference', ''), _negated=True)), _connector='OR'), name='upl_asset_claim_complete'),
        ),
        migrations.AddConstraint(
            model_name='uploadasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('release_reason_code', ''), ('released_at__isnull', True)), models.Q(('claimed_at__isnull', False), ('released_at__isnull', False), models.Q(('release_reason_code', ''), _negated=True)), _connector='OR'), name='upl_asset_release_complete'),
        ),
        migrations.AddConstraint(
            model_name='uploadasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('legal_hold_at__isnull', True), ('legal_hold_reason_code', '')), models.Q(('legal_hold_at__isnull', False), models.Q(('legal_hold_reason_code', ''), _negated=True)), _connector='OR'), name='upl_asset_hold_complete'),
        ),
        migrations.AddConstraint(
            model_name='uploadasset',
            constraint=models.CheckConstraint(condition=models.Q(('trust_status', 'legacy_trusted'), ('deleted_at__isnull', False), models.Q(('checksum_sha256', ''), _negated=True), _connector='OR'), name='upl_clean_asset_has_checksum'),
        ),
    ]
