from django.urls import path

from .views import (
    AvatarUploadView,
    ChangeEmailView,
    LoginView,
    LogoutAllView,
    LogoutView,
    MeView,
    OAuthCallbackView,
    OAuthCompleteView,
    OAuthStartView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    PasswordResetValidateView,
    RegisterView,
    RegisterEmailAvailabilityView,
    SessionListView,
    SessionRevokeOthersView,
    SessionRevokeView,
    VerificationConfirmView,
    VerificationSendView,
    TwoFactorDisableConfirmView,
    TwoFactorDisableSendView,
    EmployerBackupCodesGenerateView,
    EmployerBackupCodesSendView,
    EmployerTotpConfirmView,
    EmployerTotpDisableView,
    EmployerTotpSetupView,
    EmployerTwoFactorMethodDisableSendView,
    EmployerTwoFactorMethodDisableView,
    EmployerTwoFactorMethodsView,
    TwoFactorLoginResendView,
    TwoFactorLoginVerifyView,
    TwoFactorSetupConfirmView,
    TwoFactorSetupSendView,
)
from .views.tokens import AccountTokenRefreshView

urlpatterns = [
    path('register/', RegisterView.as_view(), name='auth-register'),
    path('register/email-availability/', RegisterEmailAvailabilityView.as_view(), name='auth-register-email-availability'),
    path('login/', LoginView.as_view(), name='auth-login'),
    path('logout/', LogoutView.as_view(), name='auth-logout'),
    path('logout-all/', LogoutAllView.as_view(), name='auth-logout-all'),
    path('sessions/', SessionListView.as_view(), name='auth-sessions'),
    path('sessions/revoke-others/', SessionRevokeOthersView.as_view(), name='auth-sessions-revoke-others'),
    path('sessions/<uuid:session_id>/', SessionRevokeView.as_view(), name='auth-session-revoke'),
    path('refresh/', AccountTokenRefreshView.as_view(), name='auth-refresh'),
    path('me/', MeView.as_view(), name='auth-me'),
    path('avatar/', AvatarUploadView.as_view(), name='auth-avatar-upload'),
    path('verify/send/', VerificationSendView.as_view(), name='auth-verify-send'),
    path('verify/confirm/', VerificationConfirmView.as_view(), name='auth-verify-confirm'),
    path('change-email/', ChangeEmailView.as_view(), name='auth-change-email'),
    path('two-factor/setup/send/', TwoFactorSetupSendView.as_view(), name='auth-two-factor-setup-send'),
    path('two-factor/setup/confirm/', TwoFactorSetupConfirmView.as_view(), name='auth-two-factor-setup-confirm'),
    path('two-factor/disable/send/', TwoFactorDisableSendView.as_view(), name='auth-two-factor-disable-send'),
    path('two-factor/disable/confirm/', TwoFactorDisableConfirmView.as_view(), name='auth-two-factor-disable-confirm'),
    path('two-factor/employer/methods/', EmployerTwoFactorMethodsView.as_view(), name='auth-employer-two-factor-methods'),
    path('two-factor/employer/totp/setup/', EmployerTotpSetupView.as_view(), name='auth-employer-totp-setup'),
    path('two-factor/employer/totp/confirm/', EmployerTotpConfirmView.as_view(), name='auth-employer-totp-confirm'),
    path('two-factor/employer/totp/disable/', EmployerTotpDisableView.as_view(), name='auth-employer-totp-disable'),
    path('two-factor/employer/methods/disable/send/', EmployerTwoFactorMethodDisableSendView.as_view(), name='auth-employer-two-factor-method-disable-send'),
    path('two-factor/employer/methods/disable/', EmployerTwoFactorMethodDisableView.as_view(), name='auth-employer-two-factor-method-disable'),
    path('two-factor/employer/backup-codes/', EmployerBackupCodesGenerateView.as_view(), name='auth-employer-backup-codes'),
    path('two-factor/employer/backup-codes/send/', EmployerBackupCodesSendView.as_view(), name='auth-employer-backup-codes-send'),
    path('two-factor/login/resend/', TwoFactorLoginResendView.as_view(), name='auth-two-factor-login-resend'),
    path('two-factor/login/verify/', TwoFactorLoginVerifyView.as_view(), name='auth-two-factor-login-verify'),
    path('password-reset/', PasswordResetRequestView.as_view(), name='auth-password-reset'),
    path('password-reset/validate/', PasswordResetValidateView.as_view(), name='auth-password-reset-validate'),
    path('password-reset/confirm/', PasswordResetConfirmView.as_view(), name='auth-password-reset-confirm'),
    path('password/', PasswordChangeView.as_view(), name='auth-password-change'),
    path('oauth/<str:provider>/start/', OAuthStartView.as_view(), name='auth-oauth-start'),
    path('oauth/<str:provider>/callback/', OAuthCallbackView.as_view(), name='auth-oauth-callback'),
    path('oauth/complete/', OAuthCompleteView.as_view(), name='auth-oauth-complete'),
]
