"""Public command API for the jobs domain."""

from .ai_generation import (
    apply_job_ai_generation_to_draft,
    cancel_job_ai_generation,
    create_job_ai_generation,
    execute_job_ai_generation,
    fail_job_ai_generation,
    job_ai_policy,
    job_ai_quota_remaining,
    purge_job_ai_generation_content,
    record_job_ai_feedback,
    recover_stale_job_ai_generations,
    sanitize_generation_input,
    sanitize_source_text,
)
from .alerts import (
    JOB_ALERT_LIMIT,
    create_job_alert,
    delete_job_alert,
    next_job_alert_run,
    reset_candidate_job_delivery_cursors,
    update_job_alert,
)
from .content_snapshot import (
    build_job_content_snapshot,
    job_pending_changes,
)
from .digests import (
    claim_due_candidate_job_digest_candidates,
    deliver_candidate_job_digest,
    due_candidate_job_digest_candidate_ids,
    pending_candidate_job_digest_ids,
    prepare_candidate_job_digest,
    purge_candidate_job_digest_history,
    release_candidate_job_digest_claim,
)
from .engagement import (
    record_consented_job_impressions,
    record_consented_job_view,
    set_viewer_cookie,
)
from .lifecycle import (
    initialize_job_visibility,
    job_lifecycle_policy,
    visibility_days_error,
)
from .moderation import (
    JobModerationStale,
    approve_job,
    create_job_review_token,
    hide_job_visibility,
    job_moderation_state,
    reject_job,
    restore_job_visibility,
)
from .posting import (
    close_job,
    create_pending_job,
    delete_job_draft,
    duplicate_job,
    employer_job_posting_context,
    extend_job_deadline,
    job_deadline_error,
    job_deadline_policy,
    publish_job,
    reopen_job,
    save_job_draft,
    update_employer_job,
)
from .reports import resolve_job_report, reverse_job_report, submit_job_report

__all__ = [
    'JOB_ALERT_LIMIT',
    'apply_job_ai_generation_to_draft',
    'cancel_job_ai_generation',
    'close_job',
    'claim_due_candidate_job_digest_candidates',
    'create_job_alert',
    'create_job_ai_generation',
    'approve_job',
    'build_job_content_snapshot',
    'create_job_review_token',
    'create_pending_job',
    'delete_job_draft',
    'delete_job_alert',
    'deliver_candidate_job_digest',
    'due_candidate_job_digest_candidate_ids',
    'duplicate_job',
    'employer_job_posting_context',
    'execute_job_ai_generation',
    'extend_job_deadline',
    'job_deadline_error',
    'initialize_job_visibility',
    'job_lifecycle_policy',
    'visibility_days_error',
    'job_deadline_policy',
    'fail_job_ai_generation',
    'publish_job',
    'pending_candidate_job_digest_ids',
    'hide_job_visibility',
    'job_moderation_state',
    'job_ai_policy',
    'job_ai_quota_remaining',
    'job_pending_changes',
    'JobModerationStale',
    'next_job_alert_run',
    'record_consented_job_view',
    'prepare_candidate_job_digest',
    'purge_candidate_job_digest_history',
    'purge_job_ai_generation_content',
    'record_consented_job_impressions',
    'record_job_ai_feedback',
    'reject_job',
    'reset_candidate_job_delivery_cursors',
    'release_candidate_job_digest_claim',
    'recover_stale_job_ai_generations',
    'restore_job_visibility',
    'reopen_job',
    'resolve_job_report',
    'reverse_job_report',
    'submit_job_report',
    'save_job_draft',
    'sanitize_generation_input',
    'sanitize_source_text',
    'set_viewer_cookie',
    'update_employer_job',
    'update_job_alert',
]
