# Generated by Django 5.1.5 on 2026-07-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
        ('jobs', '0002_job_jobskill_job_jobs_job_status_7d017a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate'], name='application_candida_6c9704_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='application_job_id_2b6ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'job'), name='uq_applications_candidate_job'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'viewed', 'shortlisted', 'interviewed', 'rejected', 'accepted'])), name='chk_applications_status'),
        ),
    ]
