# Generated by Django 5.1.5 on 2026-07-06 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('current_position', models.CharField(blank=True, max_length=255)),
                ('desired_position', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('education_level', models.CharField(blank=True, max_length=255)),
                ('expected_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_location', models.CharField(blank=True, max_length=255)),
                ('preferred_work_type', models.CharField(blank=True, choices=[('remote', 'Remote'), ('onsite', 'Onsite'), ('hybrid', 'Hybrid')], max_length=50)),
                ('job_search_status', models.CharField(blank=True, choices=[('open_to_work', 'Open to work'), ('not_looking', 'Not looking'), ('casually_looking', 'Casually looking')], max_length=50)),
                ('portfolio_url', models.TextField(blank=True)),
                ('github_url', models.TextField(blank=True)),
                ('linkedin_url', models.TextField(blank=True)),
                ('headline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('career_objective', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
