# Generated by Django 5.1.5 on 2026-07-13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0016_job_company_final'),
        ('locations', '0002_location_merged_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='job_preferences_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CandidateJobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_position_other', models.CharField(blank=True, max_length=255, null=True)),
                ('desired_salary_vnd', models.PositiveBigIntegerField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('no_experience', 'Chưa có kinh nghiệm'), ('under_1', 'Dưới 1 năm'), ('1', '1 năm'), ('2', '2 năm'), ('3', '3 năm'), ('4', '4 năm'), ('5', '5 năm'), ('over_5', 'Trên 5 năm')], max_length=20)),
                ('willing_to_relocate', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_preference', to='candidates.candidateprofile')),
            ],
            options={'db_table': 'candidate_job_preferences'},
        ),
        migrations.CreateModel(
            name='CandidateDesiredSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interested_candidates', to='jobs.jobcategory')),
                ('job_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_specializations', to='candidates.candidatejobpreference')),
            ],
            options={'db_table': 'candidate_desired_specializations', 'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='CandidatePreferredProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('job_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_provinces', to='candidates.candidatejobpreference')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_preferred_by', to='locations.location')),
            ],
            options={'db_table': 'candidate_preferred_provinces', 'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='CandidateConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('ai_recommendation', 'Gợi ý việc làm bằng AI'), ('recruiter_visibility', 'Hiển thị với nhà tuyển dụng')], max_length=30)),
                ('decision', models.CharField(choices=[('granted', 'Đồng ý'), ('denied', 'Không đồng ý')], max_length=20)),
                ('policy_version', models.CharField(default='v1', max_length=64)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='candidates.candidateprofile')),
            ],
            options={
                'db_table': 'candidate_consents',
                'constraints': [models.UniqueConstraint(fields=('candidate_profile', 'consent_type'), name='candidate_consent_type_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='candidatejobpreference',
            constraint=models.CheckConstraint(condition=models.Q(('desired_salary_vnd__isnull', True), ('desired_salary_vnd__gt', 0), _connector='OR'), name='candidate_pref_salary_positive'),
        ),
        migrations.AddConstraint(
            model_name='candidatedesiredspecialization',
            constraint=models.UniqueConstraint(fields=('job_preference', 'job_category'), name='candidate_pref_specialization_unique'),
        ),
        migrations.AddConstraint(
            model_name='candidatepreferredprovince',
            constraint=models.UniqueConstraint(fields=('job_preference', 'location'), name='candidate_pref_province_unique'),
        ),
    ]
