from django.urls import path

from .api.views import (
    AcceptDpaView,
    AllIndustryListView,
    CompanyCatalogView,
    CompanyCoverUploadView,
    CompanyDocumentContentView,
    CompanyDocumentListCreateView,
    CompanyDocumentUploadPreviewView,
    CompanyDomainClaimListCreateView,
    CompanyDomainClaimManualReviewView,
    CompanyDomainClaimRotateView,
    CompanyDomainClaimVerifyView,
    CompanyGalleryDeleteView,
    CompanyGalleryUploadView,
    CompanyLogoUploadView,
    CompanySearchView,
    CompanyUpdateRequestLifecycleView,
    CompanyUpdateRequestListCreateView,
    CreateCompanyView,
    EmployerActivityListView,
    EmployerNotificationListView,
    EmployerNotificationPreferenceView,
    EmployerNotificationReadAllView,
    EmployerNotificationReadView,
    EmployerNotificationUnreadCountView,
    IndustryListView,
    JoinCompanyView,
    MyCompanyView,
    PhoneAvailabilityView,
    PhoneChallengeView,
    RecruiterMeView,
    RecruitmentCampaignActivityView,
    RecruitmentCampaignDetailView,
    RecruitmentCampaignJobPerformanceView,
    RecruitmentCampaignListCreateView,
    RecruitmentCampaignOptionsView,
    RecruitmentCampaignPauseImpactView,
    RecruitmentCampaignReportView,
    RecruitmentCampaignStatusView,
    RecruitmentNeedDetailView,
    RecruitmentNeedListCreateView,
    RecruitmentNeedView,
    SendPhoneOtpView,
    VerifyPhoneOtpView,
)
from .api.views.registration import CompleteEmployerRegistrationView, EmployerRegisterView

urlpatterns = [
    path(
        'notifications/',
        EmployerNotificationListView.as_view(),
        name='employer-notification-list',
    ),
    path(
        'notification-preferences/',
        EmployerNotificationPreferenceView.as_view(),
        name='employer-notification-preferences',
    ),
    path(
        'notifications/unread-count/',
        EmployerNotificationUnreadCountView.as_view(),
        name='employer-notification-unread-count',
    ),
    path(
        'notifications/read-all/',
        EmployerNotificationReadAllView.as_view(),
        name='employer-notification-read-all',
    ),
    path(
        'notifications/<str:public_id>/read/',
        EmployerNotificationReadView.as_view(),
        name='employer-notification-read',
    ),
    path('activities/', EmployerActivityListView.as_view(), name='employer-activity-list'),
    path('campaigns/', RecruitmentCampaignListCreateView.as_view(), name='employer-campaign-list'),
    path(
        'campaigns/options/',
        RecruitmentCampaignOptionsView.as_view(),
        name='employer-campaign-options',
    ),
    path(
        'campaigns/<str:public_id>/',
        RecruitmentCampaignDetailView.as_view(),
        name='employer-campaign-detail',
    ),
    path(
        'campaigns/<str:public_id>/status/',
        RecruitmentCampaignStatusView.as_view(),
        name='employer-campaign-status',
    ),
    path(
        'campaigns/<str:public_id>/pause-impact/',
        RecruitmentCampaignPauseImpactView.as_view(),
        name='employer-campaign-pause-impact',
    ),
    path(
        'campaigns/<str:public_id>/activities/',
        RecruitmentCampaignActivityView.as_view(),
        name='employer-campaign-activities',
    ),
    path(
        'campaigns/<str:public_id>/report/',
        RecruitmentCampaignReportView.as_view(),
        name='employer-campaign-report',
    ),
    path(
        'campaigns/<str:public_id>/job-performance/',
        RecruitmentCampaignJobPerformanceView.as_view(),
        name='employer-campaign-job-performance',
    ),
    path('register/', EmployerRegisterView.as_view(), name='employer-register'),
    path(
        'onboarding/registration/',
        CompleteEmployerRegistrationView.as_view(),
        name='employer-registration-complete',
    ),
    path('consulting-need/', RecruitmentNeedView.as_view(), name='employer-consulting-need'),
    path(
        'recruitment-needs/',
        RecruitmentNeedListCreateView.as_view(),
        name='employer-recruitment-needs',
    ),
    path(
        'recruitment-needs/<str:public_id>/',
        RecruitmentNeedDetailView.as_view(),
        name='employer-recruitment-need-detail',
    ),
    # Nhà tuyển dụng + onboarding
    path('me/', RecruiterMeView.as_view(), name='employer-me'),
    path('phone/check/', PhoneAvailabilityView.as_view(), name='employer-phone-check'),
    path('phone/send-otp/', SendPhoneOtpView.as_view(), name='employer-phone-send-otp'),
    path(
        'phone/challenges/<str:public_id>/',
        PhoneChallengeView.as_view(),
        name='employer-phone-challenge',
    ),
    path('phone/verify/', VerifyPhoneOtpView.as_view(), name='employer-phone-verify'),
    path('dpa/accept/', AcceptDpaView.as_view(), name='employer-dpa-accept'),
    # Công ty
    path('company/', MyCompanyView.as_view(), name='employer-company'),
    path('company/create/', CreateCompanyView.as_view(), name='employer-company-create'),
    path('company/search/', CompanySearchView.as_view(), name='employer-company-search'),
    path('company/catalogs/', CompanyCatalogView.as_view(), name='employer-company-catalogs'),
    path('company/join/', JoinCompanyView.as_view(), name='employer-company-join'),
    path(
        'company/domain-claims/',
        CompanyDomainClaimListCreateView.as_view(),
        name='employer-company-domain-claims',
    ),
    path(
        'company/domain-claims/<str:public_id>/verify/',
        CompanyDomainClaimVerifyView.as_view(),
        name='employer-company-domain-claim-verify',
    ),
    path(
        'company/domain-claims/<str:public_id>/rotate/',
        CompanyDomainClaimRotateView.as_view(),
        name='employer-company-domain-claim-rotate',
    ),
    path(
        'company/domain-claims/<str:public_id>/request-manual-review/',
        CompanyDomainClaimManualReviewView.as_view(),
        name='employer-company-domain-claim-request-manual-review',
    ),
    path('company/logo/', CompanyLogoUploadView.as_view(), name='employer-company-logo-upload'),
    path('company/cover/', CompanyCoverUploadView.as_view(), name='employer-company-cover-upload'),
    path(
        'company/images/', CompanyGalleryUploadView.as_view(), name='employer-company-image-upload'
    ),
    path(
        'company/images/<int:pk>/',
        CompanyGalleryDeleteView.as_view(),
        name='employer-company-image-delete',
    ),
    path(
        'company/documents/',
        CompanyDocumentListCreateView.as_view(),
        name='employer-company-documents',
    ),
    path(
        'company/documents/preview/',
        CompanyDocumentUploadPreviewView.as_view(),
        name='employer-company-document-upload-preview',
    ),
    path(
        'company/documents/<int:pk>/content/',
        CompanyDocumentContentView.as_view(),
        name='employer-company-document-content',
    ),
    path(
        'company/update-requests/',
        CompanyUpdateRequestListCreateView.as_view(),
        name='employer-company-update-requests',
    ),
    path(
        'company/update-requests/<str:public_id>/<str:action>/',
        CompanyUpdateRequestLifecycleView.as_view(),
        name='employer-company-update-request-lifecycle',
    ),
    # Danh mục lĩnh vực
    path('industries/', IndustryListView.as_view(), name='employer-industries'),
    path('industries/all/', AllIndustryListView.as_view(), name='employer-industries-all'),
]
