# Generated by Django 5.1.5 on 2026-07-10 13:21

import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def lowercase_emails(apps, schema_editor):
    """Hạ chữ email cũ trước khi gắn ràng buộc unique trên `lower(email)`.

    Nếu môi trường nào đó đã lỡ có 2 tài khoản chỉ khác nhau hoa/thường thì dừng
    lại kèm danh sách cụ thể, thay vì để `AddConstraint` báo lỗi index khó hiểu —
    gộp hay xoá tài khoản nào là quyết định của con người, không phải migration.
    """
    User = apps.get_model('accounts', 'User')

    conflicts = (
        User.objects.annotate(lowered=Lower('email'))
        .values('lowered')
        .annotate(n=Count('id'))
        .filter(n__gt=1)
        .values_list('lowered', flat=True)
    )
    if conflicts:
        raise RuntimeError(
            'Không thể hạ chữ email: các địa chỉ sau có nhiều tài khoản chỉ khác '
            f'nhau hoa/thường, hãy gộp/xoá thủ công trước: {sorted(conflicts)}'
        )

    User.objects.update(email=Lower('email'))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authemailjob'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(lowercase_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_users_email_lower'),
        ),
    ]
