# Generated by Django 5.1.5 on 2026-07-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_two_factor_and_email_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authemailjob',
            name='kind',
            field=models.CharField(choices=[('verification', 'Email verification'), ('welcome', 'Welcome email'), ('password_reset', 'Password reset'), ('two_factor', 'Two-factor authentication code')], max_length=30),
        ),
    ]
