# Generated by Django 5.1.5 on 2026-07-18

from django.db import migrations, models


def deduplicate_welcome_jobs(apps, schema_editor):
    AuthEmailJob = apps.get_model('accounts', 'AuthEmailJob')
    duplicate_user_ids = (
        AuthEmailJob.objects.filter(kind='welcome')
        .values('user_id')
        .annotate(job_count=models.Count('id'))
        .filter(job_count__gt=1)
        .values_list('user_id', flat=True)
    )
    for user_id in duplicate_user_ids.iterator():
        jobs = AuthEmailJob.objects.filter(user_id=user_id, kind='welcome')
        keeper = jobs.order_by(
            models.Case(
                models.When(status='sent', then=0),
                default=1,
                output_field=models.IntegerField(),
            ),
            'created_at',
            'id',
        ).first()
        jobs.exclude(pk=keeper.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_authemailjob_kind'),
    ]

    operations = [
        migrations.RunPython(deduplicate_welcome_jobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='authemailjob',
            constraint=models.UniqueConstraint(
                condition=models.Q(kind='welcome'),
                fields=('user', 'kind'),
                name='uq_auth_email_welcome_per_user',
            ),
        ),
    ]
