# Generated by Django 5.1.5 on 2026-07-18 18:03

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_unique_welcome_email_per_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='socialaccount',
            name='uq_social_provider_uid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='uniq_users_email_lower',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id', 'user'), name='uq_social_provider_uid_user'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('role'), name='uniq_users_email_role_lower'),
        ),
    ]
