# Generated by Django 5.1.5 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('accounts', '0016_admin_account_management_g3')]

    operations = [
        migrations.AddIndex(
            model_name='authsession',
            index=models.Index(
                fields=['user', 'portal', 'ip_address', 'revoked_at'],
                name='auth_session_device_active_idx',
            ),
        ),
    ]
