# Generated by Django 5.1.5 on 2026-07-11 10:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_skill_groups(apps, schema_editor):
    Skill = apps.get_model('skills', 'Skill')
    SkillGroup = apps.get_model('skills', 'SkillGroup')
    groups = {}
    for category in Skill.objects.values_list('category', flat=True).distinct():
        if not category:
            continue
        group, _ = SkillGroup.objects.get_or_create(name=category, defaults={'slug': category.lower()})
        groups[category] = group
    for skill in Skill.objects.all().iterator():
        group = groups.get(skill.category)
        if group:
            Skill.objects.filter(pk=skill.pk).update(group_id=group.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='skills.skillgroup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='skills.skillgroup'),
        ),
        migrations.RunPython(backfill_skill_groups, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['group__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
    ]
