# Generated by Django 5.1.5 on 2026-07-08 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('placement', models.CharField(choices=[('footer_seo', 'Cụm link SEO (trên footer)')], default='footer_seo', max_length=30)),
                ('source', models.CharField(choices=[('manual', 'Nhập tay'), ('locations', 'Tự sinh từ Khu vực'), ('categories', 'Tự sinh từ Ngành nghề')], default='manual', max_length=20)),
                ('limit', models.PositiveSmallIntegerField(default=16, help_text='Số link tối đa khi tự sinh từ DB')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cụm link',
                'verbose_name_plural': 'Cụm link',
                'ordering': ['placement', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Định danh dùng ở code/frontend, vd: site_name', max_length=100, unique=True)),
                ('label', models.CharField(help_text='Tên hiển thị trong trang quản trị', max_length=200)),
                ('group', models.CharField(choices=[('general', 'Chung'), ('contact', 'Liên hệ'), ('appearance', 'Giao diện'), ('seo', 'SEO')], default='general', max_length=30)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_public', models.BooleanField(default=True, help_text='Cho phép trả về qua API công khai')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình site',
                'verbose_name_plural': 'Cấu hình site',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, help_text='Để trống nếu tính năng chưa có (hiển thị "Sắp ra mắt")', max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sitecontent.linkgroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
