# Generated by Django 5.1.5 on 2026-07-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('home_hero', 'Carousel trang chủ')], default='home_hero', max_length=30)),
                ('eyebrow', models.CharField(blank=True, help_text='Nhãn nhỏ phía trên tiêu đề, vd: TUYỂN DỤNG GẤP', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image_url', models.TextField(blank=True, help_text='Để trống để dùng nền gradient theo Theme bên dưới')),
                ('theme', models.CharField(choices=[('green', 'Xanh lá (thương hiệu)'), ('blue', 'Xanh dương'), ('orange', 'Cam - hồng')], default='green', max_length=20)),
                ('cta_label', models.CharField(blank=True, help_text='Để trống nếu banner không có nút bấm', max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
                'ordering': ['placement', 'order'],
            },
        ),
    ]
