# Generated by Django 5.1.5 on 2026-07-09 04:17

from django.db import migrations, models


def migrate_appearance_to_general(apps, schema_editor):
    """Nhóm 'appearance' cũ gộp vào 'general' (logo/màu là cấu hình site-wide)."""
    SiteSetting = apps.get_model('sitecontent', 'SiteSetting')
    SiteSetting.objects.filter(group='appearance').update(group='general')


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['group', 'order', 'key'], 'verbose_name': 'Cấu hình site', 'verbose_name_plural': 'Cấu hình site'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='options',
            field=models.JSONField(blank=True, default=dict, help_text='select: {"choices": [{"value","label"}]}; env: {"env_var": "TÊN_BIẾN"}'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Thứ tự hiển thị trong nhóm'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='value_type',
            field=models.CharField(choices=[('text', 'Chuỗi ngắn'), ('textarea', 'Đoạn văn'), ('number', 'Số'), ('boolean', 'Bật/tắt'), ('select', 'Chọn một'), ('color', 'Màu'), ('image', 'Ảnh'), ('email', 'Email'), ('url', 'URL'), ('json', 'JSON'), ('env', 'Cấu hình qua .env')], default='text', help_text='Kiểu dữ liệu để trang quản trị tự render form phù hợp', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='group',
            field=models.CharField(choices=[('general', 'Cài đặt chung'), ('homepage', 'Giao diện trang chủ'), ('seo', 'SEO'), ('candidate', 'Tài khoản ứng viên'), ('employer', 'Nhà tuyển dụng'), ('jobs', 'Việc làm'), ('cv', 'Hồ sơ / CV'), ('email', 'Email & thông báo'), ('payment', 'Thanh toán / gói dịch vụ'), ('security', 'Bảo mật'), ('upload', 'Upload file / media'), ('footer', 'Footer'), ('contact', 'Liên hệ / hỗ trợ'), ('admin_roles', 'Phân quyền admin'), ('ai', 'Cài đặt AI')], default='general', max_length=30),
        ),
        migrations.RunPython(migrate_appearance_to_general, migrations.RunPython.noop),
    ]
