# Generated by Django 5.1.5 on 2026-07-10 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0003_alter_sitesetting_options_sitesetting_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('suggestion', 'Góp ý cải thiện'), ('bug', 'Báo lỗi'), ('support', 'Cần hỗ trợ'), ('other', 'Khác')], default='suggestion', max_length=20)),
                ('content', models.TextField()),
                ('email', models.EmailField(blank=True, help_text='Để trống nếu người gửi không muốn nhận phản hồi', max_length=254)),
                ('page_url', models.CharField(blank=True, help_text='Trang người dùng đang xem lúc gửi', max_length=500)),
                ('status', models.CharField(choices=[('new', 'Mới'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã xử lý')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Null nếu khách gửi khi chưa đăng nhập', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Góp ý / Hỗ trợ',
                'verbose_name_plural': 'Góp ý / Hỗ trợ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='sitecontent_status_45aaf6_idx')],
            },
        ),
    ]
