# Generated by Django 5.1.5 on 2026-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, help_text='Số điện thoại nhận phản hồi (khách)', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='satisfaction',
            field=models.CharField(blank=True, choices=[('very_unsatisfied', 'Rất không hài lòng'), ('unsatisfied', 'Không hài lòng'), ('neutral', 'Bình thường'), ('satisfied', 'Hài lòng'), ('very_satisfied', 'Rất hài lòng')], help_text='Mức hài lòng người dùng chọn (nếu có)', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('ui_ux', 'Giao diện, trải nghiệm'), ('feature', 'Tính năng sản phẩm'), ('job_quality', 'Chất lượng tin tuyển dụng'), ('account', 'Tài khoản & bảo mật'), ('performance', 'Tốc độ, hiệu năng'), ('other', 'Khác')], default='feature', help_text='Chủ đề cần góp ý', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(help_text='Mô tả góp ý'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, help_text='Email nhận phản hồi (để trống nếu không cần phản hồi)', max_length=254),
        ),
    ]
