# Generated by Django 5.1.5 on 2026-07-10 19:05

from django.db import migrations, models


def seed_footer_configuration(apps, schema_editor):
    SiteSetting = apps.get_model('sitecontent', 'SiteSetting')
    LinkGroup = apps.get_model('sitecontent', 'LinkGroup')
    LinkItem = apps.get_model('sitecontent', 'LinkItem')

    # Chỉ tạo key còn thiếu; tuyệt đối không ghi đè nội dung admin đã cấu hình.
    settings = [
        ('footer_logo_url', 'Logo riêng cho footer', 'image', '',
         'Để trống để tự dùng Logo đầy đủ ở nhóm Cài đặt chung.'),
        ('footer_show_contact', 'Hiện thông tin liên hệ', 'boolean', True, ''),
        ('footer_show_apps', 'Hiện liên kết tải ứng dụng', 'boolean', True, ''),
        ('footer_show_socials', 'Hiện mạng xã hội', 'boolean', True, ''),
        ('footer_company_name', 'Tên pháp lý doanh nghiệp', 'text', '',
         'Để trống nếu chưa có pháp nhân hoặc không muốn hiển thị.'),
        ('footer_business_license', 'Thông tin giấy phép / mã số thuế', 'textarea', '', ''),
        ('footer_app_store_url', 'Link tải trên App Store', 'url', '', ''),
        ('footer_google_play_url', 'Link tải trên Google Play', 'url', '', ''),
        ('footer_qr_code_url', 'Mã QR', 'image', '',
         'QR tải ứng dụng hoặc dẫn về website. Để trống để ẩn.'),
        ('footer_qr_label', 'Nhãn dưới mã QR', 'text', '', ''),
    ]
    for order, (key, label, value_type, value, description) in enumerate(settings, start=10):
        SiteSetting.objects.get_or_create(
            key=key,
            defaults={
                'label': label,
                'group': 'footer',
                'value': value,
                'value_type': value_type,
                'options': {},
                'order': order,
                'description': description,
                'is_public': True,
            },
        )

    SiteSetting.objects.filter(key='footer_show_link_groups').update(
        label='Hiện menu điều hướng',
        description='Nội dung menu quản lý tại Cụm link, placement "Menu điều hướng footer".',
    )

    groups = [
        ('footer-about', 'Về ProCV', 1, [
            ('Giới thiệu', ''), ('Góc báo chí', ''), ('Tuyển dụng', ''), ('Liên hệ', ''),
        ]),
        ('footer-career', 'Hồ sơ & Sự nghiệp', 2, [
            ('Tìm việc làm', '/viec-lam'), ('Việc làm đã lưu', '/viec-lam-da-luu'),
            ('Tạo CV chuyên nghiệp', ''), ('Review CV bằng AI', ''),
        ]),
        ('footer-employer', 'Dành cho nhà tuyển dụng', 3, [
            ('Đăng tin tuyển dụng', '/nha-tuyen-dung'),
            ('Giải pháp tuyển dụng', '/nha-tuyen-dung/dich-vu'),
            ('Bảng giá dịch vụ', '/nha-tuyen-dung/bang-gia'),
            ('Đăng nhập nhà tuyển dụng', '/nha-tuyen-dung/dang-nhap'),
        ]),
    ]
    for key, title, order, items in groups:
        group, created = LinkGroup.objects.get_or_create(
            key=key,
            defaults={
                'title': title,
                'placement': 'footer_nav',
                'source': 'manual',
                'order': order,
                'is_active': True,
            },
        )
        if created:
            LinkItem.objects.bulk_create([
                LinkItem(group=group, label=label, url=url, order=index, is_active=True)
                for index, (label, url) in enumerate(items)
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0005_feedback_phone_feedback_satisfaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkgroup',
            name='placement',
            field=models.CharField(choices=[('footer_seo', 'Cụm link SEO (trên footer)'), ('footer_nav', 'Menu điều hướng footer')], default='footer_seo', max_length=30),
        ),
        migrations.RunPython(seed_footer_configuration, migrations.RunPython.noop),
    ]
