# Generated by Django 5.1.5 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0006_alter_linkgroup_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(
                choices=[
                    ('home_hero', 'Carousel trang chủ'),
                    ('job_detail_sidebar', 'Thẻ ảnh sidebar trang chi tiết việc làm'),
                ],
                default='home_hero',
                max_length=30,
            ),
        ),
    ]
