# Generated by Django 5.1.5 on 2026-07-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0007_alter_banner_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cta_secondary_label',
            field=models.CharField(blank=True, help_text='Nút thứ hai (vd banner blog có 2 nút)', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_secondary_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('home_hero', 'Carousel trang chủ'), ('job_detail_sidebar', 'Thẻ ảnh sidebar trang chi tiết việc làm'), ('blog_sidebar', 'Banner sidebar bài viết cẩm nang')], default='home_hero', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='group',
            field=models.CharField(choices=[('general', 'Cài đặt chung'), ('homepage', 'Giao diện trang chủ'), ('seo', 'SEO'), ('candidate', 'Tài khoản ứng viên'), ('employer', 'Nhà tuyển dụng'), ('jobs', 'Việc làm'), ('cv', 'Hồ sơ / CV'), ('email', 'Email & thông báo'), ('payment', 'Thanh toán / gói dịch vụ'), ('security', 'Bảo mật'), ('upload', 'Upload file / media'), ('footer', 'Footer'), ('contact', 'Liên hệ / hỗ trợ'), ('admin_roles', 'Phân quyền admin'), ('ai', 'Cài đặt AI'), ('blog', 'Cẩm nang nghề nghiệp (Blog)')], default='general', max_length=30),
        ),
    ]
