# Generated by Django 5.1.5 on 2026-07-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0008_banner_cta_secondary_label_banner_cta_secondary_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('home_hero', 'Carousel trang chủ'), ('job_detail_sidebar', 'Thẻ ảnh sidebar trang chi tiết việc làm'), ('blog_sidebar', 'Banner sidebar bài viết cẩm nang'), ('blog_inline', 'Banner chèn giữa trang cẩm nang')], default='home_hero', max_length=30),
        ),
    ]
