# Generated by Django 5.1.5 on 2026-07-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0012_activate_cv_builder_wysiwyg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='placement',
            field=models.CharField(choices=[('home_hero', 'Carousel trang chủ'), ('job_detail_sidebar', 'Thẻ ảnh sidebar trang chi tiết việc làm'), ('blog_sidebar', 'Banner sidebar bài viết cẩm nang'), ('blog_inline', 'Banner chèn giữa trang cẩm nang'), ('job_empty', 'Banner trang việc làm khi không có kết quả')], default='home_hero', max_length=30),
        ),
    ]
