# Generated by Django 5.1.5 on 2026-07-28 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0015_fix_employer_footer_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('internal_name', models.CharField(max_length=200)),
                ('lifecycle_state', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã phát hành'), ('paused', 'Đang tạm dừng'), ('archived', 'Đã lưu trữ')], default='draft', max_length=20)),
                ('revision_token', models.PositiveIntegerField(default=1)),
                ('dismissal_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('message_vi', models.CharField(max_length=500)),
                ('message_en', models.CharField(blank=True, max_length=500)),
                ('badge_vi', models.CharField(blank=True, max_length=80)),
                ('badge_en', models.CharField(blank=True, max_length=80)),
                ('icon', models.CharField(choices=[('alert-triangle', 'Cảnh báo'), ('bell', 'Chuông'), ('check-circle', 'Thành công'), ('info', 'Thông tin'), ('lock', 'Bảo mật'), ('megaphone', 'Loa'), ('shield', 'Khiên'), ('sparkles', 'Lấp lánh'), ('wrench', 'Bảo trì')], default='info', max_length=30)),
                ('cta_label_vi', models.CharField(blank=True, max_length=100)),
                ('cta_label_en', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=1000)),
                ('kind', models.CharField(choices=[('critical', 'Sự cố nghiêm trọng'), ('security', 'Bảo mật'), ('compliance', 'Pháp lý / tuân thủ'), ('warning', 'Cảnh báo'), ('maintenance', 'Bảo trì'), ('info', 'Thông tin'), ('success', 'Thành công'), ('event', 'Sự kiện'), ('feature', 'Tính năng')], default='info', max_length=20)),
                ('surfaces', models.JSONField(default=list)),
                ('auth_audiences', models.JSONField(default=list)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('include_path_prefixes', models.JSONField(blank=True, default=list)),
                ('exclude_path_prefixes', models.JSONField(blank=True, default=list)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(default=50)),
                ('animation', models.CharField(choices=[('slide', 'Trượt dọc'), ('fade', 'Mờ dần'), ('static', 'Tĩnh')], default='slide', max_length=20)),
                ('display_seconds', models.PositiveSmallIntegerField(default=6)),
                ('dismiss_mode', models.CharField(choices=[('locked', 'Không thể đóng'), ('close', 'Đóng'), ('snooze', 'Tạm ẩn')], default='close', max_length=20)),
                ('snooze_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='sitecontent.announcement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_revisions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['announcement_id', '-number'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('surface', models.CharField(choices=[('candidate', 'Ứng viên'), ('employer_marketing', 'Trang nhà tuyển dụng'), ('employer_workspace', 'Workspace nhà tuyển dụng'), ('admin_workspace', 'Workspace quản trị')], max_length=30)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('unique_impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('unique_clicks', models.PositiveBigIntegerField(default=0)),
                ('dismisses', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='sitecontent.announcementrevision')),
            ],
            options={
                'ordering': ['-date', 'surface'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='active_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sitecontent.announcementrevision'),
        ),
        migrations.CreateModel(
            name='AnnouncementUserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissal_version', models.PositiveIntegerField()),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='sitecontent.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_states', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='announcementrevision',
            index=models.Index(fields=['announcement', '-number'], name='site_ann_rev_number_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementrevision',
            index=models.Index(fields=['starts_at', 'ends_at'], name='site_ann_rev_schedule_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementrevision',
            constraint=models.UniqueConstraint(fields=('announcement', 'number'), name='uq_site_ann_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='announcementrevision',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='chk_site_ann_rev_number'),
        ),
        migrations.AddConstraint(
            model_name='announcementrevision',
            constraint=models.CheckConstraint(condition=models.Q(('priority__gte', 0), ('priority__lte', 1000)), name='chk_site_ann_priority'),
        ),
        migrations.AddConstraint(
            model_name='announcementrevision',
            constraint=models.CheckConstraint(condition=models.Q(('display_seconds__gte', 4), ('display_seconds__lte', 15)), name='chk_site_ann_display_seconds'),
        ),
        migrations.AddConstraint(
            model_name='announcementrevision',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__isnull', True), ('starts_at__lt', models.F('ends_at')), _connector='OR'), name='chk_site_ann_schedule'),
        ),
        migrations.AddConstraint(
            model_name='announcementrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'critical'), _negated=True), ('ends_at__isnull', False), _connector='OR'), name='chk_site_ann_critical_end'),
        ),
        migrations.AddConstraint(
            model_name='announcementrevision',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('dismiss_mode', 'snooze'), _negated=True), models.Q(('snooze_seconds__gte', 60), ('snooze_seconds__isnull', False)), _connector='OR'), name='chk_site_ann_snooze_seconds'),
        ),
        migrations.AddIndex(
            model_name='announcementdailymetric',
            index=models.Index(fields=['date', 'surface'], name='site_ann_metric_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementdailymetric',
            constraint=models.UniqueConstraint(fields=('announcement_revision', 'date', 'surface'), name='uq_site_ann_metric_day_surface'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['lifecycle_state', '-updated_at'], name='site_ann_state_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle_state__in', ['draft', 'published', 'paused', 'archived'])), name='chk_site_ann_lifecycle'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('revision_token__gte', 1)), name='chk_site_ann_revision_token'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.CheckConstraint(condition=models.Q(('dismissal_version__gte', 1)), name='chk_site_ann_dismiss_version'),
        ),
        migrations.AddIndex(
            model_name='announcementuserstate',
            index=models.Index(fields=['user', 'announcement'], name='site_ann_state_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementuserstate',
            constraint=models.UniqueConstraint(fields=('user', 'announcement', 'dismissal_version'), name='uq_site_ann_user_state'),
        ),
        migrations.AddConstraint(
            model_name='announcementuserstate',
            constraint=models.CheckConstraint(condition=models.Q(('dismissal_version__gte', 1)), name='chk_site_ann_state_version'),
        ),
        migrations.AddConstraint(
            model_name='announcementuserstate',
            constraint=models.CheckConstraint(condition=models.Q(('dismissed_at__isnull', True), ('snoozed_until__isnull', True), _connector='OR'), name='chk_site_ann_one_state'),
        ),
    ]
