# Generated by Django 5.1.5 on 2026-08-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0016_announcement_announcementrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementrevision',
            name='background_fit',
            field=models.CharField(choices=[('cover', 'Phủ toàn dải'), ('repeat-x', 'Lặp ngang'), ('contain', 'Vừa khung')], default='cover', max_length=20),
        ),
        migrations.AddField(
            model_name='announcementrevision',
            name='background_image',
            field=models.TextField(blank=True, default='', help_text='Storage key ảnh nền strip (vd. site/announcements/backgrounds/…)'),
        ),
        migrations.AddField(
            model_name='announcementrevision',
            name='background_overlay',
            field=models.CharField(choices=[('none', 'Không phủ'), ('light', 'Phủ sáng'), ('dark', 'Phủ tối')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='announcementrevision',
            name='background_position',
            field=models.CharField(choices=[('center', 'Giữa'), ('top', 'Trên'), ('bottom', 'Dưới')], default='center', max_length=20),
        ),
        migrations.AddField(
            model_name='announcementrevision',
            name='color_accent',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='announcementrevision',
            name='color_bg_from',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='announcementrevision',
            name='color_bg_to',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='announcementrevision',
            name='color_fg',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='announcementrevision',
            name='theme_mode',
            field=models.CharField(choices=[('kind', 'Theo loại thông báo'), ('preset', 'Bảng màu có sẵn'), ('custom', 'Màu tùy chỉnh')], default='kind', max_length=20),
        ),
        migrations.AddField(
            model_name='announcementrevision',
            name='theme_preset',
            field=models.CharField(blank=True, choices=[('brand', 'Thương hiệu'), ('emerald', 'Xanh ngọc'), ('amber', 'Hổ phách'), ('rose', 'Hồng'), ('violet', 'Tím'), ('slate', 'Xám'), ('ocean', 'Xanh biển')], default='', max_length=20),
        ),
    ]
