# Generated by Django 5.1.5 on 2026-07-06 19:26

from django.db import migrations, models


def copy_location_to_locations(apps, schema_editor):
    """Move each job's single location into the new many-to-many field."""
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.all():
        if job.location_id:
            job.locations.add(job.location_id)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_jobskill_job_jobs_job_status_7d017a_idx_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_locatio_11d7ca_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('none', 'Không yêu cầu'), ('high_school', 'THPT'), ('intermediate', 'Trung cấp'), ('college', 'Cao đẳng'), ('university', 'Đại học'), ('postgraduate', 'Sau đại học')], max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='number_of_vacancies',
            field=models.PositiveIntegerField(blank=True, help_text='Số lượng cần tuyển; null = không giới hạn', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='locations.location'),
        ),
        migrations.RunPython(copy_location_to_locations, noop),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
