# Generated by Django 5.1.5 on 2026-07-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobcategory_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_years',
            field=models.CharField(blank=True, choices=[('none', 'Không yêu cầu'), ('under_1', 'Dưới 1 năm'), ('1', '1 năm'), ('2', '2 năm'), ('3', '3 năm'), ('4', '4 năm'), ('5', '5 năm'), ('over_5', 'Trên 5 năm')], help_text='Số năm kinh nghiệm yêu cầu (bộ lọc "Kinh nghiệm")', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='position_level',
            field=models.CharField(blank=True, choices=[('employee', 'Nhân viên'), ('team_lead', 'Trưởng nhóm'), ('manager', 'Trưởng/Phó phòng'), ('supervisor', 'Quản lý / Giám sát'), ('branch_manager', 'Trưởng chi nhánh'), ('vice_director', 'Phó giám đốc'), ('director', 'Giám đốc'), ('intern', 'Thực tập sinh')], help_text='Cấp bậc tuyển dụng (bộ lọc "Cấp bậc")', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='weekend_policy',
            field=models.CharField(blank=True, choices=[('work_saturday', 'Làm thứ 7'), ('off_saturday', 'Nghỉ thứ 7')], help_text='Chế độ thứ 7; để trống = tin không đề cập', max_length=20),
        ),
    ]
