# Generated by Django 5.1.5 on 2026-07-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='has_flash_badge',
            field=models.BooleanField(default=False, help_text='Huy hiệu Sấm Chớp — NTD tương tác nhanh'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='Nhãn HOT (đỏ) trên card'),
        ),
        migrations.AddField(
            model_name='job',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Nhãn GẤP / tuyển gấp (cam) trên card'),
        ),
        migrations.AddField(
            model_name='job',
            name='tier',
            field=models.CharField(choices=[('standard', 'Tin thường'), ('featured', 'Tin nổi bật'), ('top', 'Tin TOP')], default='standard', max_length=20),
        ),
    ]
