# Generated by Django 5.1.5 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_has_flash_badge_job_is_hot_job_is_urgent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='application_instructions',
            field=models.TextField(blank=True, help_text='Hướng dẫn ứng tuyển hiển thị trên trang chi tiết, có thể nhập HTML định dạng.'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule',
            field=models.TextField(blank=True, help_text='Thời gian làm việc hiển thị trên trang chi tiết, có thể nhập HTML định dạng.'),
        ),
    ]
