# Generated by Django 5.1.5 on 2026-07-11 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_normalized_job_data(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    JobCategory = apps.get_model('jobs', 'JobCategory')
    JobCategoryAssignment = apps.get_model('jobs', 'JobCategoryAssignment')
    JobLocation = apps.get_model('jobs', 'JobLocation')
    Benefit = apps.get_model('jobs', 'Benefit')
    Language = apps.get_model('jobs', 'Language')

    JobCategory.objects.filter(parent__isnull=True).update(category_type='occupation_group')
    JobCategory.objects.filter(parent__isnull=False, parent__parent__isnull=True).update(category_type='domain')
    JobCategory.objects.filter(parent__parent__isnull=False).update(category_type='specialization')

    Benefit.objects.bulk_create([
        Benefit(name='Bảo hiểm xã hội', slug='bao-hiem-xa-hoi', sort_order=10),
        Benefit(name='Thưởng tháng 13', slug='thuong-thang-13', sort_order=20),
        Benefit(name='Phụ cấp', slug='phu-cap', sort_order=30),
        Benefit(name='Đào tạo', slug='dao-tao', sort_order=40),
        Benefit(name='Du lịch', slug='du-lich', sort_order=50),
        Benefit(name='Khám sức khỏe', slug='kham-suc-khoe', sort_order=60),
    ], ignore_conflicts=True)
    Language.objects.bulk_create([
        Language(name='Tiếng Anh', code='en', slug='tieng-anh'),
        Language(name='Tiếng Hàn', code='ko', slug='tieng-han'),
        Language(name='Tiếng Nhật', code='ja', slug='tieng-nhat'),
        Language(name='Tiếng Trung', code='zh', slug='tieng-trung'),
        Language(name='Tiếng Pháp', code='fr', slug='tieng-phap'),
    ], ignore_conflicts=True)

    for job in Job.objects.prefetch_related('locations').iterator(chunk_size=200):
        if job.category_id:
            JobCategoryAssignment.objects.get_or_create(
                job_id=job.pk,
                category_id=job.category_id,
                role='primary_specialization',
            )

        salary_updates = {}
        if not job.is_salary_visible or (job.salary_min is None and job.salary_max is None):
            salary_updates['salary_type'] = 'negotiable'
            if not job.is_salary_visible:
                salary_updates['salary_min'] = None
                salary_updates['salary_max'] = None
        elif job.salary_min is not None and job.salary_max is not None:
            salary_updates['salary_type'] = 'fixed' if job.salary_min == job.salary_max else 'range'
        elif job.salary_min is not None:
            salary_updates['salary_type'] = 'from'
        else:
            salary_updates['salary_type'] = 'up_to'

        description = job.description or ''
        if job.responsibilities:
            description = f'{description}\n<h3>Trách nhiệm công việc</h3>\n{job.responsibilities}'.strip()
        requirements = job.requirements or ''
        if job.nice_to_have:
            requirements = f'{requirements}\n<h3>Điểm ưu tiên</h3>\n{job.nice_to_have}'.strip()
        schedule_note = job.work_schedule or ''
        if job.weekend_policy and job.weekend_policy not in schedule_note:
            weekend_text = 'Làm việc thứ 7' if job.weekend_policy == 'work_saturday' else 'Nghỉ thứ 7'
            schedule_note = f'{schedule_note}\n{weekend_text}'.strip()

        Job.objects.filter(pk=job.pk).update(
            description=description,
            requirements=requirements,
            work_schedule_note=schedule_note,
            **salary_updates,
        )

        old_locations = list(job.locations.all())
        for location in old_locations:
            JobLocation.objects.get_or_create(
                job_id=job.pk,
                location_id=location.pk,
                address_detail=job.address if len(old_locations) == 1 else '',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_employerprofile_has_brand_page'),
        ('jobs', '0012_job_application_instructions_job_work_schedule'),
        ('locations', '0002_location_merged_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicationContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobCategoryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary_specialization', 'Vị trí chuyên môn chính'), ('domain_knowledge', 'Kiến thức chuyên ngành')], max_length=30)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobLanguageRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(blank=True, choices=[('basic', 'Cơ bản'), ('conversational', 'Giao tiếp'), ('working', 'Làm việc'), ('professional', 'Thành thạo'), ('native', 'Bản ngữ')], max_length=30)),
                ('certificate', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('is_required', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_detail', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobWorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekday_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_overnight', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='age_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='age_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='gender_requirement',
            field=models.CharField(choices=[('any', 'Không yêu cầu'), ('male', 'Nam'), ('female', 'Nữ')], default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_type',
            field=models.CharField(choices=[('negotiable', 'Thỏa thuận'), ('range', 'Khoảng lương'), ('fixed', 'Mức cố định'), ('from', 'Từ mức'), ('up_to', 'Đến mức')], default='negotiable', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='work_schedule_note',
            field=models.TextField(blank=True, help_text='Mô tả lịch không thể hiện hết bằng các khung giờ có cấu trúc.'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='category_type',
            field=models.CharField(choices=[('occupation_group', 'Nhóm nghề'), ('domain', 'Kiến thức chuyên ngành'), ('specialization', 'Vị trí chuyên môn')], default='specialization', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('none', 'Không yêu cầu'), ('middle_school', 'Trung học cơ sở (Cấp 2)'), ('high_school', 'Trung học phổ thông (Cấp 3)'), ('intermediate', 'Trung cấp'), ('college', 'Cao đẳng'), ('university', 'Đại học'), ('postgraduate', 'Cao học')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Hợp đồng'), ('seasonal', 'Thời vụ'), ('internship', 'Internship'), ('freelance', 'Freelance')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['experience_years'], name='jobs_job_experie_46959c_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['position_level'], name='jobs_job_positio_4718a7_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['education_level'], name='jobs_job_educati_13a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'published_at'], name='jobs_job_status_d968cf_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['employer', 'status', '-created_at'], name='jobs_job_employe_43f916_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('age_min__isnull', True), models.Q(('age_min__gte', 15), ('age_min__lte', 100)), _connector='OR'), name='chk_jobs_age_min_range'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('age_max__isnull', True), models.Q(('age_max__gte', 15), ('age_max__lte', 100)), _connector='OR'), name='chk_jobs_age_max_range'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('age_min__isnull', True), ('age_max__isnull', True), ('age_max__gte', models.F('age_min')), _connector='OR'), name='chk_jobs_age_order'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_vacancies__isnull', True), ('number_of_vacancies__gte', 1), _connector='OR'), name='chk_jobs_vacancies_positive'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('salary_type', 'range'), _negated=True), models.Q(('salary_max__isnull', False), ('salary_min__isnull', False), ('salary_max__gte', models.F('salary_min'))), _connector='OR'), name='chk_jobs_salary_range'),
        ),
        migrations.AddField(
            model_name='jobapplicationcontact',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_contact', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobapplicationemail',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='jobs.jobapplicationcontact'),
        ),
        migrations.AddField(
            model_name='jobbenefit',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_assignments', to='jobs.benefit'),
        ),
        migrations.AddField(
            model_name='jobbenefit',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_benefits', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='jobcategoryassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_assignments', to='jobs.jobcategory'),
        ),
        migrations.AddField(
            model_name='jobcategoryassignment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='joblanguagerequirement',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_requirements', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_locations', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='joblocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_workplaces', to='locations.location'),
        ),
        migrations.AddField(
            model_name='jobworkschedule',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='joblanguagerequirement',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirements', to='jobs.language'),
        ),
        migrations.AddConstraint(
            model_name='jobapplicationemail',
            constraint=models.UniqueConstraint(fields=('contact', 'email'), name='uq_job_contact_email'),
        ),
        migrations.AddConstraint(
            model_name='jobbenefit',
            constraint=models.UniqueConstraint(fields=('job', 'benefit'), name='uq_job_benefit'),
        ),
        migrations.AddIndex(
            model_name='jobcategoryassignment',
            index=models.Index(fields=['category', 'role', 'job'], name='jobs_jobcat_categor_34092e_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobcategoryassignment',
            constraint=models.UniqueConstraint(fields=('job', 'category', 'role'), name='uq_job_category_assignment'),
        ),
        migrations.AddConstraint(
            model_name='jobcategoryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'primary_specialization')), fields=('job',), name='uq_job_primary_specialization'),
        ),
        migrations.AddIndex(
            model_name='joblocation',
            index=models.Index(fields=['location', 'job'], name='jobs_jobloc_locatio_392c01_idx'),
        ),
        migrations.AddConstraint(
            model_name='joblocation',
            constraint=models.UniqueConstraint(fields=('job', 'location', 'address_detail'), name='uq_job_location_address'),
        ),
        migrations.AddConstraint(
            model_name='jobworkschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday_from__isnull', True), ('weekday_from__range', (1, 7)), _connector='OR'), name='chk_job_schedule_weekday_from'),
        ),
        migrations.AddConstraint(
            model_name='jobworkschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday_to__isnull', True), ('weekday_to__range', (1, 7)), _connector='OR'), name='chk_job_schedule_weekday_to'),
        ),
        migrations.AddIndex(
            model_name='joblanguagerequirement',
            index=models.Index(fields=['language', 'proficiency_level'], name='jobs_joblan_languag_514b2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='joblanguagerequirement',
            constraint=models.UniqueConstraint(fields=('job', 'language'), name='uq_job_language'),
        ),
        migrations.RunPython(backfill_normalized_job_data, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_experie_09027f_idx',
        ),
        migrations.RemoveField(model_name='job', name='address'),
        migrations.RemoveField(model_name='job', name='application_instructions'),
        migrations.RemoveField(model_name='job', name='category'),
        migrations.RemoveField(model_name='job', name='experience_level'),
        migrations.RemoveField(model_name='job', name='is_salary_visible'),
        migrations.RemoveField(model_name='job', name='locations'),
        migrations.RemoveField(model_name='job', name='nice_to_have'),
        migrations.RemoveField(model_name='job', name='responsibilities'),
        migrations.RemoveField(model_name='job', name='short_description'),
        migrations.RemoveField(model_name='job', name='weekend_policy'),
        migrations.RemoveField(model_name='job', name='work_schedule'),
    ]
