# Generated by Django 5.1.5 on 2026-07-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0007_migrate_employer_profiles_to_companies'),
        ('jobs', '0013_benefit_jobapplicationcontact_jobapplicationemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_jobs', to='employers.company'),
        ),
    ]
