# Generated by Django 5.1.5 on 2026-07-22 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0016_recruitmentcampaign'),
        ('jobs', '0019_jobcategorylocalization_locale_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('actor_role', models.CharField(choices=[('employer', 'Nhà tuyển dụng'), ('system', 'Hệ thống')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='employers.recruitmentcampaign'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['campaign', 'status'], name='jobs_job_campaign_status_idx'),
        ),
        migrations.AddField(
            model_name='jobstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobstatushistory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='jobs.job'),
        ),
        migrations.AddIndex(
            model_name='jobstatushistory',
            index=models.Index(fields=['job', '-created_at'], name='job_status_history_idx'),
        ),
    ]
