# Generated by Django 5.1.5 on 2026-07-22

from django.db import migrations, models


def backfill_job_submission_timestamps(apps, schema_editor):
    """Preserve quota history for postings created before review was mandatory."""
    job_model = apps.get_model('jobs', 'Job')
    job_model.objects.filter(submitted_at__isnull=True, published_at__isnull=False).update(
        submitted_at=models.F('published_at')
    )
    job_model.objects.filter(
        submitted_at__isnull=True,
        status__in=['pending', 'active', 'closed', 'rejected'],
    ).update(submitted_at=models.F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_jobstatushistory_job_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_job_submission_timestamps, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='jobstatushistory',
            name='actor_role',
            field=models.CharField(
                choices=[
                    ('employer', 'Nhà tuyển dụng'),
                    ('admin', 'Quản trị viên'),
                    ('system', 'Hệ thống'),
                ],
                max_length=20,
            ),
        ),
    ]
