# Generated by Django 5.1.5 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_job_submitted_at_and_admin_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Nháp'),
                    ('pending', 'Chờ duyệt'),
                    ('active', 'Đang tuyển'),
                    ('closed', 'Đã đóng'),
                    ('rejected', 'Từ chối'),
                ],
                default='draft',
                max_length=50,
            ),
        ),
    ]
