# Generated by Django 5.1.5 on 2026-07-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0022_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('full_time', 'Full-time'),
                    ('part_time', 'Part-time'),
                    ('contract', 'Hợp đồng'),
                    ('seasonal', 'Thời vụ'),
                    ('work_from_home', 'Làm tại nhà (việc làm phổ thông)'),
                    ('internship', 'Internship'),
                    ('freelance', 'Freelance'),
                    ('other', 'Khác'),
                ],
                max_length=50,
            ),
        ),
    ]
