# Generated by Django 5.1.5 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0023_alter_job_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='income_display_type',
            field=models.CharField(
                choices=[
                    ('income', 'Thu nhập'),
                    ('income_at_kpi', 'Thu nhập khi đạt 100% KPI'),
                ],
                default='income',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('negotiable', 'Thỏa thuận'),
                    ('range', 'Khoảng lương'),
                    ('fixed', 'Mức cố định'),
                    ('from', 'Từ mức'),
                    ('up_to', 'Đến mức'),
                ],
                default='negotiable',
                max_length=20,
                null=True,
            ),
        ),
    ]
