# Generated by Django 5.1.5 on 2026-07-26 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_remove_jobs_one_job_per_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('fake_company', 'Công ty không có thật'), ('scam', 'Lừa đảo, thu phí ứng viên'), ('wrong_info', 'Thông tin tin đăng sai sự thật'), ('duplicate', 'Tin trùng lặp'), ('expired', 'Tin đã tuyển xong nhưng chưa gỡ'), ('other', 'Lý do khác')], max_length=30)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('upheld', 'Xác nhận vi phạm'), ('dismissed', 'Bác bỏ')], default='pending', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobs.job')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='jobs_report_status_idx'), models.Index(fields=['job', 'status'], name='jobs_report_job_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('job', 'reporter'), name='jobs_unique_report_per_reporter')],
            },
        ),
    ]
