# Generated by Django 5.1.5 on 2026-07-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0029_jobreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobReportResolutionEvent',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'public_id',
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    'from_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Chờ xử lý'),
                            ('upheld', 'Xác nhận vi phạm'),
                            ('dismissed', 'Bác bỏ'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'to_status',
                    models.CharField(
                        choices=[
                            ('pending', 'Chờ xử lý'),
                            ('upheld', 'Xác nhận vi phạm'),
                            ('dismissed', 'Bác bỏ'),
                        ],
                        max_length=20,
                    ),
                ),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='job_report_resolution_events',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'report',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='resolution_history',
                        to='jobs.jobreport',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [
                    models.Index(
                        fields=['report', 'created_at'],
                        name='jobs_report_event_idx',
                    ),
                ],
            },
        ),
    ]
