# Generated by Django 5.2.2 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_jobreportresolutionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(
                choices=[('VND', 'VND'), ('USD', 'USD')],
                default='VND',
                max_length=20,
            ),
        ),
    ]
