# Generated by Django 5.1.14 on 2026-07-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0032_job_policy_hold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='moderation_hold',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Không giữ'),
                    ('manual_review', 'Tạm ẩn để rà soát nội dung'),
                    ('confirmed_violation', 'Tạm ẩn do vi phạm đã xác nhận'),
                ],
                default='',
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_held_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('action', models.CharField(choices=[('approve', 'Duyệt tin'), ('reject', 'Từ chối tin'), ('hide', 'Tạm ẩn tin'), ('restore', 'Khôi phục hiển thị')], max_length=20)),
                ('reason_code', models.CharField(blank=True, choices=[('incomplete_content', 'Nội dung chưa đầy đủ'), ('misleading_content', 'Nội dung gây hiểu nhầm'), ('prohibited_content', 'Nội dung bị cấm'), ('fraud_risk', 'Có dấu hiệu lừa đảo'), ('duplicate_posting', 'Tin trùng lặp'), ('confirmed_report', 'Báo cáo vi phạm đã xác nhận'), ('other', 'Lý do khác')], max_length=40)),
                ('note', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(blank=True, max_length=50)),
                ('from_hold', models.CharField(blank=True, max_length=24)),
                ('to_hold', models.CharField(blank=True, max_length=24)),
                ('content_fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderation_events', to='jobs.job')),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_events', to='jobs.jobreport')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['moderation_hold', 'status'], name='jobs_moderation_hold_idx'),
        ),
        migrations.AddIndex(
            model_name='jobmoderationevent',
            index=models.Index(fields=['job', '-created_at'], name='job_moderation_event_idx'),
        ),
    ]
