# Generated by Django 5.1.5 on 2026-08-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_job_moderation_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='approved_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='job',
            name='approved_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
