# Generated by Django 5.1.5 on 2026-08-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0034_job_approved_snapshot_job_approved_snapshot_at'),
        ('locations', '0002_location_merged_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateJobDigest',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('message_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('scheduled_for', models.DateTimeField()),
                ('source_alert_public_ids', models.JSONField(blank=True, default=list)),
                ('includes_suitable_recommendations', models.BooleanField(default=False)),
                ('source_windows', models.JSONField(blank=True, default=dict)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_auth_revision', models.PositiveBigIntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Chờ gửi'),
                            ('sending', 'Đang gửi'),
                            ('sent', 'Đã gửi'),
                            ('empty', 'Không có việc làm mới'),
                            ('skipped', 'Bỏ qua theo cài đặt'),
                            ('failed', 'Gửi thất bại'),
                            ('cancelled', 'Đã hủy'),
                        ],
                        default='pending',
                        max_length=16,
                    ),
                ),
                ('job_count', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='job_alert_digests',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='CandidateJobDigestSchedule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('suitable_cursor_at', models.DateTimeField()),
                ('suitable_next_run_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'candidate',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='job_digest_schedule',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('keyword', models.CharField(max_length=255)),
                (
                    'keyword_scope',
                    models.CharField(
                        choices=[
                            ('title', 'Tên việc làm'),
                            ('company', 'Tên công ty'),
                            ('both', 'Tên việc làm hoặc công ty'),
                        ],
                        default='title',
                        max_length=16,
                    ),
                ),
                (
                    'salary_bucket',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('u10', 'Dưới 10 triệu'),
                            ('10-15', '10 - 15 triệu'),
                            ('15-20', '15 - 20 triệu'),
                            ('20-25', '20 - 25 triệu'),
                            ('25-30', '25 - 30 triệu'),
                            ('30-50', '30 - 50 triệu'),
                            ('o50', 'Trên 50 triệu'),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    'experience_years',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('none', 'Không yêu cầu'),
                            ('under_1', 'Dưới 1 năm'),
                            ('1', '1 năm'),
                            ('2', '2 năm'),
                            ('3', '3 năm'),
                            ('4', '4 năm'),
                            ('5', '5 năm'),
                            ('over_5', 'Trên 5 năm'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'work_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('onsite', 'Onsite'),
                            ('remote', 'Remote'),
                            ('hybrid', 'Hybrid'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'employment_type',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('full_time', 'Full-time'),
                            ('part_time', 'Part-time'),
                            ('contract', 'Hợp đồng'),
                            ('seasonal', 'Thời vụ'),
                            ('work_from_home', 'Làm tại nhà (việc làm phổ thông)'),
                            ('internship', 'Internship'),
                            ('freelance', 'Freelance'),
                            ('other', 'Khác'),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    'frequency',
                    models.CharField(
                        choices=[('daily', 'Hằng ngày'), ('weekly', 'Hằng tuần')],
                        default='daily',
                        max_length=16,
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                ('criteria_fingerprint', models.CharField(max_length=64)),
                ('cursor_at', models.DateTimeField()),
                ('next_run_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='job_alerts',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='candidate_job_alerts',
                        to='jobs.jobcategory',
                    ),
                ),
                (
                    'province',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='locations.location',
                    ),
                ),
                (
                    'ward',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='locations.location',
                    ),
                ),
            ],
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.CreateModel(
            name='CandidateJobDigestItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'source_kind',
                    models.CharField(
                        choices=[
                            ('configured_alert', 'Thông báo đã cài đặt'),
                            ('suitable_recommendation', 'Việc làm phù hợp'),
                        ],
                        max_length=32,
                    ),
                ),
                ('job_published_at', models.DateTimeField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('match_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('source_alert_public_ids', models.JSONField(blank=True, default=list)),
                ('includes_suitable_recommendation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'digest',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='jobs.candidatejobdigest',
                    ),
                ),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='jobs.job',
                    ),
                ),
                (
                    'source_alert',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='digest_items',
                        to='jobs.jobalert',
                    ),
                ),
            ],
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.CreateModel(
            name='CandidateJobEmailReceipt',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('job_published_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField()),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'digest',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='receipts',
                        to='jobs.candidatejobdigest',
                    ),
                ),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='jobs.job',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='candidatejobdigest',
            index=models.Index(
                fields=['status', 'created_at'],
                name='job_digest_status_time_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='candidatejobdigest',
            constraint=models.UniqueConstraint(
                fields=('candidate', 'scheduled_for'),
                name='uq_job_digest_candidate_schedule',
            ),
        ),
        migrations.AddIndex(
            model_name='candidatejobdigestschedule',
            index=models.Index(
                fields=['suitable_next_run_at'],
                name='job_digest_suitable_due_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(
                fields=['candidate', '-created_at'],
                name='job_alert_candidate_time_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='jobalert',
            index=models.Index(
                fields=['is_active', 'next_run_at'],
                name='job_alert_due_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='jobalert',
            constraint=models.UniqueConstraint(
                fields=('candidate', 'criteria_fingerprint'),
                name='uq_job_alert_candidate_fingerprint',
            ),
        ),
        migrations.AddIndex(
            model_name='candidatejobdigestitem',
            index=models.Index(
                fields=['candidate', 'job'],
                name='jdi_candidate_job_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='candidatejobdigestitem',
            constraint=models.UniqueConstraint(
                fields=('digest', 'job'),
                name='uq_job_digest_item_job',
            ),
        ),
        migrations.AddIndex(
            model_name='candidatejobemailreceipt',
            index=models.Index(
                fields=['candidate', 'job'],
                name='job_email_receipt_lookup_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='candidatejobemailreceipt',
            constraint=models.UniqueConstraint(
                fields=('candidate', 'job'),
                name='uq_candidate_job_email_receipt',
            ),
        ),
    ]
