# Generated by Django 5.1.5 on 2026-08-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_alert_category(apps, schema_editor):
    """Preserve alerts created before category selection became multi-value."""
    JobAlert = apps.get_model('jobs', 'JobAlert')
    JobAlertCategory = apps.get_model('jobs', 'JobAlertCategory')
    links = [
        JobAlertCategory(alert_id=alert_id, category_id=category_id)
        for alert_id, category_id in JobAlert.objects.exclude(category_id=None).values_list(
            'id',
            'category_id',
        )
    ]
    JobAlertCategory.objects.bulk_create(links, ignore_conflicts=True)


def restore_primary_alert_category(apps, schema_editor):
    """Best-effort rollback: keep one deterministic category per alert."""
    JobAlert = apps.get_model('jobs', 'JobAlert')
    JobAlertCategory = apps.get_model('jobs', 'JobAlertCategory')
    primary_by_alert = {}
    for alert_id, category_id in JobAlertCategory.objects.order_by(
        'alert_id',
        'category_id',
    ).values_list('alert_id', 'category_id'):
        primary_by_alert.setdefault(alert_id, category_id)
    alerts = list(JobAlert.objects.filter(pk__in=primary_by_alert))
    for alert in alerts:
        alert.category_id = primary_by_alert[alert.pk]
    JobAlert.objects.bulk_update(alerts, ['category'])


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0035_candidate_job_alerts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlertCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'alert',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='category_links',
                        to='jobs.jobalert',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='candidate_job_alert_links',
                        to='jobs.jobcategory',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobalertcategory',
            constraint=models.UniqueConstraint(
                fields=('alert', 'category'),
                name='uq_job_alert_category',
            ),
        ),
        migrations.RunPython(copy_existing_alert_category, restore_primary_alert_category),
        migrations.RemoveField(
            model_name='jobalert',
            name='category',
        ),
        migrations.AddField(
            model_name='jobalert',
            name='categories',
            field=models.ManyToManyField(
                blank=True,
                related_name='candidate_job_alerts',
                through='jobs.JobAlertCategory',
                to='jobs.jobcategory',
            ),
        ),
        migrations.AddField(
            model_name='candidatejobdigestitem',
            name='source_alert_fingerprints',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='CandidateJobEmailSuppression',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('first_sent_at', models.DateTimeField()),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'job',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='jobs.job',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='candidatejobemailsuppression',
            constraint=models.UniqueConstraint(
                fields=('candidate', 'job'),
                name='uq_candidate_job_email_suppression',
            ),
        ),
    ]
