# Generated by Django 5.1.5 on 2026-08-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_job_alert_multi_category_and_suppression'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='auto_reject_after_days',
            field=models.PositiveSmallIntegerField(choices=[(14, '2 tuần'), (21, '3 tuần'), (28, '4 tuần'), (42, '6 tuần'), (56, '8 tuần')], default=21),
        ),
        migrations.AddField(
            model_name='job',
            name='auto_reject_stale_applications',
            field=models.BooleanField(default=False, help_text='Tự chuyển hồ sơ chờ xử lý quá hạn sang trạng thái từ chối.'),
        ),
        migrations.AddField(
            model_name='job',
            name='auto_rejection_email_body',
            field=models.TextField(default='Cảm ơn bạn đã ứng tuyển vị trí {job_title} tại {company_name}.\n\nSau {auto_reject_weeks} tuần kể từ ngày ứng tuyển, chúng tôi chưa thể phản hồi hồ sơ của bạn. Điều này thường có nghĩa là hồ sơ hiện chưa phù hợp với vị trí này.\n\nTuy nhiên, thông tin của bạn đã được lưu trong hệ thống của {company_name} và nhà tuyển dụng vẫn có thể liên hệ nếu có vị trí phù hợp hơn sau này.', help_text='Nội dung email gửi ứng viên ba ngày sau khi hồ sơ bị tự động từ chối.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='auto_reject_stale_applications',
            field=models.BooleanField(default=True, help_text='Tự chuyển hồ sơ chờ xử lý quá hạn sang trạng thái từ chối.'),
        ),
    ]
