# Generated by Django 5.1.5 on 2026-08-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.jobs.models.ai_generation


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0037_job_auto_reject_after_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAiGeneration',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                (
                    'mode',
                    models.CharField(
                        choices=[('ai_brief', 'Brief có hướng dẫn'), ('jd_text', 'JD có sẵn')],
                        max_length=20,
                    ),
                ),
                ('locale', models.CharField(default='vi-VN', max_length=16)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('queued', 'Đang chờ'),
                            ('processing', 'Đang xử lý'),
                            ('completed', 'Hoàn tất'),
                            ('failed', 'Thất bại'),
                            ('cancelled', 'Đã hủy'),
                        ],
                        default='queued',
                        max_length=20,
                    ),
                ),
                (
                    'phase',
                    models.CharField(
                        choices=[
                            ('queued', 'Đang chờ'),
                            ('preparing_context', 'Chuẩn bị dữ liệu'),
                            ('generating', 'Đang tạo nội dung'),
                            ('validating', 'Đang kiểm tra'),
                            ('completed', 'Hoàn tất'),
                            ('failed', 'Thất bại'),
                            ('cancelled', 'Đã hủy'),
                        ],
                        default='queued',
                        max_length=32,
                    ),
                ),
                ('sanitized_input', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('unresolved_suggestions', models.JSONField(blank=True, default=dict)),
                (
                    'manual_fields',
                    models.JSONField(
                        default=apps.jobs.models.ai_generation.default_job_ai_manual_fields
                    ),
                ),
                ('idempotency_key', models.CharField(max_length=64)),
                ('request_hash', models.CharField(editable=False, max_length=64)),
                ('quota_day', models.DateField()),
                ('model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(default='job-post-v2', max_length=32)),
                ('schema_version', models.CharField(default='job-post-v2', max_length=32)),
                ('provider_attempts', models.PositiveSmallIntegerField(default=0)),
                ('invocation_id', models.BigIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_diff', models.JSONField(blank=True, default=dict)),
                (
                    'feedback',
                    models.CharField(
                        blank=True,
                        choices=[('helpful', 'Hữu ích'), ('not_helpful', 'Chưa hữu ích')],
                        max_length=20,
                    ),
                ),
                (
                    'feedback_reason',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('accuracy', 'Độ chính xác'),
                            ('relevance', 'Độ liên quan'),
                            ('writing_quality', 'Chất lượng diễn đạt'),
                            ('taxonomy', 'Danh mục/kỹ năng'),
                            ('other', 'Khác'),
                        ],
                        max_length=32,
                    ),
                ),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('content_purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'applied_job',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='ai_generations',
                        to='jobs.job',
                    ),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='job_ai_generations',
                        to='employers.company',
                    ),
                ),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='job_ai_generations',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [
                    models.Index(fields=['owner', 'quota_day'], name='jobs_ai_owner_quota_idx'),
                    models.Index(
                        fields=['status', 'lease_expires_at'], name='jobs_ai_status_lease_idx'
                    ),
                    models.Index(
                        fields=['created_at', 'content_purged_at'], name='jobs_ai_retention_idx'
                    ),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('owner', 'idempotency_key'),
                        name='uq_job_ai_generation_owner_idempotency',
                    )
                ],
            },
        ),
    ]
