# Generated by Django 5.1.5 on 2026-07-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('cvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='cvs.usercv'),
        ),
    ]
