# Generated by Django 5.1.5 on 2026-07-22 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_multiple_locations_and_contact'),
        ('cvs', '0010_cvasset'),
        ('jobs', '0019_jobcategorylocalization_locale_ref'),
        ('locations', '0002_location_merged_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='application',
            name='chk_applications_status',
        ),
        migrations.AddField(
            model_name='application',
            name='employer_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('viewed', 'Viewed'), ('considering', 'Considering'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='submitted', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'viewed', 'considering', 'shortlisted', 'interviewed', 'rejected', 'accepted'])), name='chk_applications_status'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application'),
        ),
        migrations.AddField(
            model_name='applicationstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['application', 'created_at'], name='app_status_history_idx'),
        ),
    ]
