# Generated by Django 5.1.5 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_applicationstatushistory_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='uq_applications_candidate_job',
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(
                fields=['candidate', 'job', 'applied_at'],
                name='idx_app_candidate_job_date',
            ),
        ),
    ]
