# Generated by Django 5.1.5 on 2026-08-11 22:07

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_allow_limited_reapplications'),
        ('cvs', '0010_cvasset'),
        ('jobs', '0037_job_auto_reject_after_days_and_more'),
        ('locations', '0002_location_merged_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='auto_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='auto_rejection_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='auto_rejection_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'status_updated_at'], name='app_auto_status_due_idx'),
        ),
    ]
