# Generated by Django 5.1.5 on 2026-07-06 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv_templates', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('cv_type', models.CharField(choices=[('builder', 'Builder'), ('uploaded', 'Uploaded')], max_length=50)),
                ('source', models.CharField(choices=[('builder', 'Builder'), ('uploaded', 'Uploaded'), ('imported', 'Imported')], default='builder', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('cv_data', models.JSONField(blank=True, default=dict)),
                ('style_config', models.JSONField(blank=True, default=dict)),
                ('file_url', models.TextField(blank=True)),
                ('pdf_url', models.TextField(blank=True)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, help_text='pdf, docx', max_length=50)),
                ('raw_text', models.TextField(blank=True)),
                ('normalized_text', models.TextField(blank=True)),
                ('current_version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('last_exported_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvs', to='cv_templates.cvtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CvSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_extracted', 'AI extracted')], default='manual', max_length=50)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('evidence_text', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_skills', to='skills.skill')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_skills', to='cvs.usercv')),
            ],
        ),
        migrations.AddIndex(
            model_name='usercv',
            index=models.Index(fields=['user', 'is_default'], name='cvs_usercv_user_id_1424e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercv',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'uploaded', 'processing', 'analyzed', 'failed'])), name='chk_user_cvs_status'),
        ),
        migrations.AddConstraint(
            model_name='cvskill',
            constraint=models.UniqueConstraint(fields=('cv', 'skill'), name='uq_cv_skills_cv_skill'),
        ),
    ]
