/* oxlint-disable react/only-export-components -- Lazy route registry exports component values. */
import { lazy } from 'react'

export const HomePage = lazy(() => import('@/pages/main/home/Home'))
export const JobListPage = lazy(() => import('@/pages/main/jobs/JobList'))
export const JobDetailPage = lazy(() => import('@/pages/main/jobs/JobDetail'))
export const SavedJobsPage = lazy(() => import('@/pages/main/jobs/SavedJobs'))
export const MainLoginPage = lazy(() => import('@/pages/main/auth/Login'))
export const MainRegisterPage = lazy(() => import('@/pages/main/auth/Register'))
export const VerifyEmailPage = lazy(() => import('@/pages/main/auth/VerifyEmail'))
export const CandidateAccountLayout = lazy(() => import('@/pages/main/account/CandidateAccountLayout'))
export const AccountPlaceholderPage = lazy(() => import('@/pages/main/account/AccountPlaceholder'))
export const PersonalInfoPage = lazy(() => import('@/pages/main/account/PersonalInfo'))
export const MyCvsPage = lazy(() => import('@/pages/main/account/MyCvs'))
export const TwoFactorAuthenticationPage = lazy(() => import('@/pages/main/account/TwoFactorAuthentication'))
export const JobPreferenceSettingsPage = lazy(() => import('@/pages/main/account/JobPreferenceSettings'))
export const OnboardUserPage = lazy(() => import('@/pages/main/onboarding/OnboardUser'))
export const OnboardUserSettingPage = lazy(() => import('@/pages/main/onboarding/OnboardUserSetting'))
export const BlogHomePage = lazy(() => import('@/pages/main/blog/BlogHome'))
export const BlogCategoryPage = lazy(() => import('@/pages/main/blog/BlogCategory'))
export const BlogDetailPage = lazy(() => import('@/pages/main/blog/BlogDetail'))
export const ForgotPasswordPage = lazy(() => import('@/pages/main/auth/ForgotPassword'))
export const ResetPasswordPage = lazy(() => import('@/pages/main/auth/ResetPassword'))
export const OAuthCallbackPage = lazy(() => import('@/pages/main/auth/OAuthCallback'))
export const CookiePolicyPage = lazy(() => import('@/pages/main/legal/CookiePolicy'))
export const TemplateCatalogPage = lazy(() => import('@/pages/main/cv-templates/TemplateCatalog'))
export const TemplateDetailPage = lazy(() => import('@/pages/main/cv-templates/TemplateDetail'))
export const CvEditorPage = lazy(() => import('@/pages/main/cvs/CvEditor'))
export const CvOwnerViewPage = lazy(() => import('@/pages/main/cvs/CvOwnerView'))
export const CvSharedViewPage = lazy(() => import('@/pages/main/cvs/CvSharedView'))
