# Generated by Django 5.1.5 on 2026-07-06 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('level', models.CharField(choices=[('province', 'Province'), ('ward', 'Ward')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('ward_type', models.CharField(blank=True, help_text='xã, phường, đặc khu — chỉ khi level=ward', max_length=20)),
                ('province_type', models.CharField(blank=True, help_text='tỉnh, thành phố trực thuộc trung ương — chỉ khi level=province', max_length=20)),
                ('country', models.CharField(default='Vietnam', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='locations.location')),
            ],
            options={
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['level'], name='locations_l_level_d02177_idx'), models.Index(fields=['name'], name='locations_l_name_0dcc82_idx')],
            },
        ),
    ]
