# Generated by Django 5.1.5 on 2026-07-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='merged_from',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
