export const MODULE_LABELS = {
  account: 'Quản lý tài khoản',
  admin_access: 'Quản lý phân quyền',
  audit_log: 'Lịch sử hệ thống',
  blog: 'Bài viết',
  company: 'Công ty & nhà tuyển dụng',
  company_update: 'Cập nhật thông tin công ty',
  consultation_lead: 'Lead tư vấn',
  cv_template: 'Catalogue CV',
  dashboard: 'Tổng quan',
  employer_verification: 'Xác thực nhà tuyển dụng',
  job_moderation: 'Kiểm duyệt tin',
  knowledgebase: 'FAQ & hướng dẫn',
  service_catalog: 'Dịch vụ nhà tuyển dụng',
  service_audit: 'Lịch sử dịch vụ',
  service_entitlement: 'Kho lượt dịch vụ',
  site_setting: 'Cài đặt hệ thống',
}
