# Generated by Django 5.1.5 on 2026-08-12 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case', models.CharField(max_length=64)),
                ('correlation_key', models.CharField(blank=True, max_length=128)),
                ('provider', models.CharField(max_length=32)),
                ('provider_backend', models.CharField(choices=[('gemini_developer', 'Gemini Developer API'), ('vertex', 'Vertex AI')], max_length=32)),
                ('model', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=64)),
                ('prompt_sha256', models.CharField(max_length=64)),
                ('schema_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('started', 'Started'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='started', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('cached_tokens', models.PositiveBigIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=16)),
                ('latency_ms', models.PositiveBigIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('provider_request_id', models.CharField(blank=True, max_length=255)),
                ('finish_reason', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_invocations',
                'indexes': [models.Index(fields=['-created_at'], name='ai_inv_created_idx'), models.Index(fields=['use_case', 'status', '-created_at'], name='ai_inv_use_status_idx'), models.Index(fields=['correlation_key', '-created_at'], name='ai_inv_correlation_idx'), models.Index(fields=['provider', 'model', '-created_at'], name='ai_inv_provider_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('status', 'started')), models.Q(models.Q(('status', 'started'), _negated=True), ('completed_at__isnull', False)), _connector='OR'), name='ai_inv_completion_valid'), models.CheckConstraint(condition=models.Q(('attempt_count__gte', models.F('retry_count'))), name='ai_inv_attempts_gte_retries')],
            },
        ),
        migrations.CreateModel(
            name='AiUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('use_case', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=32)),
                ('provider_backend', models.CharField(choices=[('gemini_developer', 'Gemini Developer API'), ('vertex', 'Vertex AI')], max_length=32)),
                ('model', models.CharField(max_length=128)),
                ('invocation_count', models.PositiveBigIntegerField(default=0)),
                ('success_count', models.PositiveBigIntegerField(default=0)),
                ('failure_count', models.PositiveBigIntegerField(default=0)),
                ('quota_rejection_count', models.PositiveBigIntegerField(default=0)),
                ('retry_count', models.PositiveBigIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('cached_tokens', models.PositiveBigIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('total_latency_ms', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_usage_daily',
                'ordering': ['-date', 'use_case', 'provider', 'model'],
                'indexes': [models.Index(fields=['date', 'use_case'], name='ai_usage_date_use_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'use_case', 'provider', 'provider_backend', 'model'), name='ai_usage_daily_unique')],
            },
        ),
    ]
